var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var f=0;return function(){return f<c.length?{done:!1,value:c[f++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var f="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return f?f.call(c):$jscomp.arrayIterator(c)};
$jscomp.getGlobal=function(c){c=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var f=0;f<c.length;++f){var h=c[f];if(h&&h.Math==Math)return h}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,f,h){c!=Array.prototype&&c!=Object.prototype&&(c[f]=h.value)};$jscomp.polyfill=function(c,f,h,q){if(f){h=$jscomp.global;c=c.split(".");for(q=0;q<c.length-1;q++){var E=c[q];E in h||(h[E]={});h=h[E]}c=c[c.length-1];q=h[c];f=f(q);f!=q&&null!=f&&$jscomp.defineProperty(h,c,{configurable:!0,writable:!0,value:f})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function f(){this.batch_=null}function h(c){return c instanceof E?c:new E(function(f,xc){f(c)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;f.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var f=this;this.asyncExecuteFunction(function(){f.executeBatch_()})}this.batch_.push(c)};var q=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(c){q(c,0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=
this.batch_;this.batch_=[];for(var f=0;f<c.length;++f){var h=c[f];c[f]=null;try{h()}catch(na){this.asyncThrow_(na)}}}this.batch_=null};f.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var E=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{c(f.resolve,f.reject)}catch(lb){f.reject(lb)}};E.prototype.createResolveAndReject_=function(){function c(c){return function(xc){h||(h=!0,c.call(f,xc))}}var f=this,
h=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};E.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof E)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var f=null!=c;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};E.prototype.resolveToNonPromiseObj_=function(c){var f=void 0;try{f=c.then}catch(lb){this.reject_(lb);return}"function"==
typeof f?this.settleSameAsThenable_(f,c):this.fulfill_(c)};E.prototype.reject_=function(c){this.settle_(2,c)};E.prototype.fulfill_=function(c){this.settle_(1,c)};E.prototype.settle_=function(c,f){if(0!=this.state_)throw Error("Cannot settle("+c+", "+f+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=f;this.executeOnSettledCallbacks_()};E.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)Hb.asyncExecute(this.onSettledCallbacks_[c]);
this.onSettledCallbacks_=null}};var Hb=new f;E.prototype.settleSameAsPromise_=function(c){var f=this.createResolveAndReject_();c.callWhenSettled_(f.resolve,f.reject)};E.prototype.settleSameAsThenable_=function(c,f){var h=this.createResolveAndReject_();try{c.call(f,h.resolve,h.reject)}catch(na){h.reject(na)}};E.prototype.then=function(c,f){function h(c,f){return"function"==typeof c?function(f){try{q(c(f))}catch(Ib){ba(Ib)}}:f}var q,ba,xc=new E(function(c,f){q=c;ba=f});this.callWhenSettled_(h(c,q),
h(f,ba));return xc};E.prototype.catch=function(c){return this.then(void 0,c)};E.prototype.callWhenSettled_=function(c,f){function h(){switch(q.state_){case 1:c(q.result_);break;case 2:f(q.result_);break;default:throw Error("Unexpected state: "+q.state_);}}var q=this;null==this.onSettledCallbacks_?Hb.asyncExecute(h):this.onSettledCallbacks_.push(h)};E.resolve=h;E.reject=function(c){return new E(function(f,h){h(c)})};E.race=function(c){return new E(function(f,q){for(var E=$jscomp.makeIterator(c),ba=
E.next();!ba.done;ba=E.next())h(ba.value).callWhenSettled_(f,q)})};E.all=function(c){var f=$jscomp.makeIterator(c),q=f.next();return q.done?h([]):new E(function(c,E){function ba(f){return function(h){na[f]=h;Oa--;0==Oa&&c(na)}}var na=[],Oa=0;do na.push(void 0),Oa++,h(q.value).callWhenSettled_(ba(na.length-1),E),q=f.next();while(!q.done)})};return E},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(c,f){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function c(h){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(h||"")+"_"+f++,h)}var f=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.underscoreProtoCanBeSet=function(){var c={a:!0},f={};try{return f.__proto__=c,f.a}catch(h){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(c,f){c.__proto__=f;if(c.__proto__!==f)throw new TypeError(c+" is not extensible");return c}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(c){if(!(c instanceof Object))throw new TypeError("Iterator result "+c+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(c){this.yieldResult=c};$jscomp.generator.Context.prototype.throw_=function(c){this.abruptCompletion_={exception:c,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(c){this.abruptCompletion_={return:c};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(c){this.abruptCompletion_={jumpTo:c};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(c,f){this.nextAddress=f;return{value:c}};$jscomp.generator.Context.prototype.yieldAll=function(c,f){c=$jscomp.makeIterator(c);var h=c.next();$jscomp.generator.ensureIteratorResultIsObject_(h);if(h.done)this.yieldResult=h.value,this.nextAddress=f;else return this.yieldAllIterator_=c,this.yield(h.value,f)};
$jscomp.generator.Context.prototype.jumpTo=function(c){this.nextAddress=c};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(c,f){this.catchAddress_=c;void 0!=f&&(this.finallyAddress_=f)};$jscomp.generator.Context.prototype.setFinallyBlock=function(c){this.catchAddress_=0;this.finallyAddress_=c||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(c,f){this.nextAddress=c;this.catchAddress_=f||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(c){this.catchAddress_=c||0;c=this.abruptCompletion_.exception;this.abruptCompletion_=null;return c};$jscomp.generator.Context.prototype.enterFinallyBlock=function(c,f,h){h?this.finallyContexts_[h]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=c||0;this.finallyAddress_=f||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(c,f){f=this.finallyContexts_.splice(f||0)[0];if(f=this.abruptCompletion_=this.abruptCompletion_||f){if(f.isException)return this.jumpToErrorHandler_();void 0!=f.jumpTo&&this.finallyAddress_<f.jumpTo?(this.nextAddress=f.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=c};$jscomp.generator.Context.prototype.forIn=function(c){return new $jscomp.generator.Context.PropertyIterator(c)};
$jscomp.generator.Context.PropertyIterator=function(c){this.object_=c;this.properties_=[];for(var f in c)this.properties_.push(f);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var c=this.properties_.pop();if(c in this.object_)return c}return null};$jscomp.generator.Engine_=function(c){this.context_=new $jscomp.generator.Context;this.program_=c};
$jscomp.generator.Engine_.prototype.next_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,c,this.context_.next_);this.context_.next_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(c){this.context_.start_();var f=this.context_.yieldAllIterator_;if(f)return this.yieldAllStep_("return"in f?f["return"]:function(c){return{value:c,done:!0}},c,this.context_.return);this.context_.return(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(c){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],c,this.context_.next_);this.context_.throw_(c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(c,f,h){try{var q=c.call(this.context_.yieldAllIterator_,f);$jscomp.generator.ensureIteratorResultIsObject_(q);if(!q.done)return this.context_.stop_(),q;var E=q.value}catch(Hb){return this.context_.yieldAllIterator_=null,this.context_.throw_(Hb),this.nextStep_()}this.context_.yieldAllIterator_=null;h.call(this.context_,E);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var c=this.program_(this.context_);if(c)return this.context_.stop_(),{value:c.value,done:!1}}catch(f){this.context_.yieldResult=void 0,this.context_.throw_(f)}this.context_.stop_();if(this.context_.abruptCompletion_){c=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(c.isException)throw c.exception;return{value:c.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(c){this.next=function(f){return c.next_(f)};this.throw=function(f){return c.throw_(f)};this.return=function(f){return c.return_(f)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(c,f){f=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(f));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(f,c.prototype);return f};
$jscomp.asyncExecutePromiseGenerator=function(c){function f(f){return c.next(f)}function h(f){return c.throw(f)}return new Promise(function(q,E){function Hb(c){c.done?q(c.value):Promise.resolve(c.value).then(f,h).then(Hb,E)}Hb(c.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(c){return $jscomp.asyncExecutePromiseGenerator(c())};$jscomp.asyncExecutePromiseGeneratorProgram=function(c){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c)))};
$jscomp.iteratorFromArray=function(c,f){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var h=0,q={next:function(){if(h<c.length){var E=h++;return{value:f(E,c[E]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill("Array.prototype.fill",function(c){return c?c:function(c,h,q){var f=this.length||0;0>h&&(h=Math.max(0,f+h));if(null==q||q>f)q=f;q=Number(q);0>q&&(q=Math.max(0,f+q));for(h=Number(h||0);h<q;h++)this[h]=c;return this}},"es6","es3");
function PEvs(c,f,h,q,E,Hb,xc){var ba,lb,na,Le,rd,Qf,Oa,Xb,Ib,fa,mb,Jb=0,Yb=0,Zd,Pa=!1,yc=!1,Zb=0,nb=0,$b=0,rb=0,sd,Nc,$d=3,ac=function(c){Oa=c.target;for(Ib=Xb=0;Oa;)Xb+=Oa.offsetLeft-Oa.scrollLeft,Ib+=Oa.offsetTop-Oa.scrollTop,Oa=Oa.offsetParent;Jb=(Pa?sd:c.pageX)-Xb-document.body.scrollLeft;Yb=(Pa?Nc:c.pageY)-Ib-document.body.scrollTop};this.getX=function(){return Jb};this.getY=function(){return Yb};this.setHysteresis=function(c){$d=c};var F=function(c){c.preventDefault();c.stopImmediatePropagation?
c.stopImmediatePropagation():c.stopPropagation()},ae=function(c){ac(c);Zd=Jb;xa=Yb;V=!0;null!=ha&&(Le=(new Date).getTime());null!=oa&&oa(c)},L=function(c){V&&(ac(c),V=!1,null!=sb&&sb(c),null!=ha&&(rd=(new Date).getTime(),Qf=rd-Le,300>Qf&&ha(c)))},Ka=function(c){ac(c);Math.abs(Jb-Zd)<$d&&Math.abs(Yb-xa)<$d||(xa=Zd=-9999,V?null!=Wa&&Wa(c):null!=ob&&ob(c),null!=be&&Me())};this.touchDown=function(c){na=!0;if(1<c.targetTouches.length)return Pa=!0,mb&&(nb=-1,F(c)),!1;ba=c.changedTouches;lb=ba[0];ae(lb)};
this.touchUp=function(c){0==c.targetTouches.length&&(Pa=na=!1);F(c);if(Pa||yc)return Pa||(yc=!1),!1;ba=c.changedTouches;lb=ba[0];L(lb)};this.touchMove=function(c){na=!0;F(c);if(Pa)return mb&&(ba=c.targetTouches,sd=(ba[0].pageX+ba[1].pageX)/2,Nc=(ba[0].pageY+ba[1].pageY)/2,yc=!0,$b=ba[0].pageX-ba[1].pageX,rb=ba[0].pageY-ba[1].pageY,Zb=$b*$b+rb*rb,ac(c),mb&&0<nb&&30<Math.abs(Zb-nb)&&mb(0<Zb-nb?1:-1),nb=Zb),!1;ba=c.changedTouches;lb=ba[0];Ka(lb)};this.pointUp=function(c){F(c);for(var f=0;f<ya.length;f++)if(ya[f].pointerId==
c.pointerId){ya.splice(f,1);break}0==ya.length&&(na=Pa=!1);if(Pa||yc)return Pa||(yc=!1),!1;L(c);return!1};this.pointDown=function(c){F(c);ya.push(c);nb=-1;na=!0;1<ya.length?Pa=!0:ae(c);return!1};this.pointMove=function(c){F(c);for(var f=0;f<ya.length;f++)ya[f].pointerId==c.pointerId&&(ya[f]=c);if(Pa||!yc){if(Pa)return sd=(ya[0].pageX+ya[1].pageX)/2,Nc=(ya[0].pageY+ya[1].pageY)/2,ac(c),mb&&(yc=!0,$b=ya[0].pageX-ya[1].pageX,rb=ya[0].pageY-ya[1].pageY,Zb=$b*$b+rb*rb,mb&&0<nb&&30<Math.abs(Zb-nb)&&mb(0<
Zb-nb?1:-1),nb=Zb),!1;Ka(c);return!1}};this.mouseDown=function(c){na||(F(c),ae(c))};this.clearDown=function(){V=!1};this.mouseUp=function(c){na||(F(c),L(c))};this.useWheel=function(f){c.addEventListener("wheel",this.mouseWheel,!0);mb=f};this.mouseWheel=function(c){ac(c);var f=Math.max(-1,Math.min(1,-c.deltaY||-c.detail));F(c);mb&&mb(f)};this.mouseClick=function(c){F(c);V=!1};this.mouseMove=function(c){na||(F(c),Ka(c))};this.mouseDragged=function(c){na||(F(c),ac(c),null!=Wa&&Wa(c),null!=be&&Me())};
var Me=function(){clearTimeout(fa);fa=setTimeout(function(){be()},600)};var xa=Zd=Yb=Jb=0;var oa=f;var sb=h;var ob=q;var Wa=E;var ha=Hb;var be=xc;var V=na=!1;var ya=[];c.addEventListener("mousedown",this.mouseDown,!1);c.addEventListener("mouseup",this.mouseUp,!1);c.addEventListener("mousemove",this.mouseMove,!1);c.addEventListener("click",this.mouseClick,!1);c.addEventListener("touchstart",this.touchDown,!1);c.addEventListener("touchend",this.touchUp,!1);c.addEventListener("touchmove",this.touchMove,
!1);c.addEventListener("touchleave",this.touchUp,!1);c.addEventListener("touchcancel",this.touchUp,!1);c.addEventListener("contextmenu",function(c){c.preventDefault()},!1);c.style["touch-action"]="none";c.addEventListener("mouseout",function(c){V||(Yb=Jb=-1,null!=ob&&ob(c));V=!1})};var HAniSF=function(){function c(b){var a,g;td=!0;if(b instanceof Array)for(e={},null!=hh&&(b=b.concat(hh)),a=0;a<b.length;a++){if(!(2>b[a].length)){var d=b[a].trim();if(0!=d.indexOf("#")){var c=d.indexOf("=");if(!(1>c)){var S=d.substr(0,c).trim().toLowerCase();e[S]=d.substr(c+1).trim()}}}}else e=b;Ne=!1;a=e.debug;null!=a&&("true"==a?(Rf=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),Ne=!0,ia("HAniS Version 4.43")):Ne=!1);a=e.no_initial_focus;null!=a&&"false"!=a||u.focus();
pb=!0;z(e.set_className,"f")&&(pb=!1);ia("Is type of param an array = "+(b instanceof Array));a=e.divalign;null!=a&&(ce=a.trim(),u.align=ce);z(e.prevent_shortcuts,"t")&&(Oe=!0);a=e.initial_message;null!=a&&(b=e.initial_message_style,null==b&&(b="background-color:red;top:10px;left:10px;height:100px;width:200px"),b="z-index:99;position:absolute;"+b,zc=p("div"),zc.setAttribute("style",b),zc.innerHTML=a,zc.addEventListener("click",function(){zc.style.visibility="hidden"},!1),zc.style.visibility="visible",
Xa.appendChild(zc),b=e.initial_message_timeout,null!=b&&("auto"==b?Sf=!0:(Sf=!1,b=parseInt(e.initial_message_timeout,10),2>b&&(b=2),setTimeout(function(){zc.style.visibility="hidden"},1E3*b))));ud=null;a=e.initial_enhancement;null!=a&&(ud=parseInt(a,10)-1);vd=!1;Pe="X = ";Qe=" Y = ";a=e.coordinates;null!=a&&(E(a),vd=!0,Pe="Lat = ",Qe=" Lon = ");d="green";c="white";S="12px Arial";var Q=null,l=g=10,k=10;Tf=2;a=e.keyboard_propagate;null!=a&&z(a,"t")&&(Re=!1);a=e.coordinates_display_style;null!=a&&(b=
a.split(","),d=b[0].trim(),c=b[1].trim(),S=b[2].trim(),3<b.length&&(Pe=b[3],Qe=b[4],Tf=parseInt(b[5],10),6<b.length&&(Q=b[6].trim(),g=parseInt(b[7],10),l=parseInt(b[8],10),k=parseInt(b[9],10))));ih=new ob(d,c,S,Q,g,l,k);Se=Pc=null;null!=e.map_scale&&(Te=bc=!0,b=e.map_scale.split(","),Pc=parseFloat(b[0]),Se=1<b.length?parseFloat(b[1]):Pc);wd=vd?"km":" ";Ue=1;a=e.distance_unit;null!=a&&(wd=a.trim(),z(wd,"mi")&&(Ue=.621371192),z(wd,"nm")&&(Ue=.539956803),z(wd,"na")&&(Ue=.539956803));de=null;a=e.show_bearing;
null!=a&&(de=a.trim());a=e.divcan_style;null!=a&&a.trim();Uf="default";a=e.distance_cursor;null!=a&&(Uf=a.trim());Ve="default";a=e.location_cursor;null!=a&&(Ve=a.trim());We="default";a=e.probe_cursor;null!=a&&(We=a.trim());Vf="default";a=e.mark_cursor;null!=a&&(Vf=a.trim());a=e.imagecan_style;null!=a&&(b=a.trim()+";position:absolute;top:0;left:0;",tb.setAttribute("style",b+"z-index:1;"),Ac.setAttribute("style",b+"z-index:12;"));d="blue";c="white";S="12px Arial";Q=null;k=l=g=10;Wf=1;jh="white";a=e.distance_display_style;
null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),jh=5<=b.length?b[4].trim():c,S=b[2].trim(),Wf=parseInt(b[3],10),5<b.length&&(Q=b[5].trim(),g=parseInt(b[6],10),l=parseInt(b[7],10),k=parseInt(b[8],10)));Gi=new ob(d,c,S,Q,g,l,k);d="black";c="white";S="12px Arial";Q=null;k=l=g=10;a=e.probe_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),S=b[2].trim(),3<b.length&&(Q=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Hi=new ob(d,c,S,Q,g,l,k);kh="Undefined";
lh=!1;ee=0;a=e.probe_undefined;null!=a&&(b=a.split(","),kh=b[0].trim(),1<b.length&&(ee=parseInt(b[1],10)+1),2<b.length&&(lh=!0));Xf=!1;e.probe_base_image&&(Xf=!0);a=e.active_probe;null!=a&&(cc=!0);a=e.pause;null!=a&&(mh=parseInt(a,10));a=e.auto_refresh;null!=a&&(Yf=6E4*parseInt(a,10),Qc=setInterval("HAniS.reloadFOF();",Yf),fe=!0);Xe=!1;nh="#FFFFFF80";a=e.show_hotspots;null!=a&&(b=a.split(","),z(b[0],"t")&&(Xe=!0),1<b.length&&(nh=b[1]));Zf=!1;z(e.center_hotspots,"t")&&(Zf=!0);xd=!1;z(e.enable_smoothing,
"t")&&(xd=!0);oh="low";a=e.smoothing_quality;null!=a&&(oh=a);Ye=!0;z(e.check_image_size,"f")&&(Ye=!1);ph=!1;a=e.sprites;if(null!=a){b=a.split(",");$f=new Image;ag=[];bg=[];dc=[];ec=[];if("row"==b[1].trim().toLowerCase())for(l=c=d=0,a=2;a<b.length;)for("row"==b[a].trim().toLowerCase()&&(d=0,c+=l,l=0,a+=1),g=parseInt(b[a],10),a+=1,S=parseInt(b[a],10),a+=1,Q=parseInt(b[a],10),Q>l&&(l=Q),a+=1,k=0;k<g;k++)ag.push(d),bg.push(c),dc.push(S),ec.push(Q),d+=S;else for(c=!1,a=1;a<b.length;)ag.push(parseInt(b[a],
10)),a+=1,bg.push(parseInt(b[a],10)),a+=1,a>=b.length?(d=0,c=!0):d=parseInt(b[a],10),0>d?(c=!0,dc.push(Math.abs(d)),a+=1,d=parseInt(b[a++],10),ec.push(Math.abs(d))):c?(dc.push(dc[dc.length-1]),ec.push(ec[ec.length-1])):(dc.push(parseInt(b[a],10)),a+=1,ec.push(parseInt(b[a],10)),a+=1);$f.onload=function(){ph=!0};$f.src=b[0]}a=e.overlay_labels;null!=a&&(fc=a.split(","));cg=null;a=e.auto_enhance_background;null!=a&&(cg=parseInt(a,10)-1);Rc=null;a=e.auto_enhance;if(null!=a)for(d=e.overlay_probe_table,
b=a.split(","),Rc=Array(b.length),a=0;a<b.length;a++)"x"==b[a].trim().toLowerCase()?Rc[a]=-1:Rc[a]=parseInt(b[a].trim(),10)-1,null==d&&(Bc[a]=Rc[a]);Sc=!1;ub=-1;a=e.overlay_enhance;null!=a&&(Sc=!0,ub=parseInt(a,10)-1);Cc=null;yd=!0;a=e.overlay_allow_hoverzones;if(null!=a)for(b=a.split(","),Cc=Array(b.length),a=0;a<b.length;a++)if(Cc[a]=!0,z(b[a],"n")||z(b[a],"f"))Cc[a]=!1;P=O=null;ge=qh=!1;a=e.window_size;null!=a&&(b=a.split(","),"div"==b[0]?ge=!0:(P=2*Math.floor(parseInt(b[0],10)/2),O=2*Math.floor(parseInt(b[1],
10)/2)),qh=!0);dg=[];a=e.framenumber_index_values;null!=a&&(dg=a.split(","));Kb=[];a=e.use_for_all_frames;if(null!=a)for(b=a.split(","),a=0;a<b.length;a+=2)Kb[parseInt(b[a],10)]=parseInt(b[a+1],10)-1;he=-1;a=e.skip_missing;null!=a&&(he=parseInt(a,10));rh="#00000000";a=e.skip_missing_color;null!=a&&(rh=a);Ze=null;a=e.overlay_spacer;if(null!=a)for(b=a.split(","),Ze=Array(b.length),a=0;a<b.length;a++)Ze[a]=parseInt(b[a],10);a=e.overlay_probe_table;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)"x"==
b[a].trim().toLowerCase()?Bc[a]=-1:Bc[a]=parseInt(b[a],10)-1;eg=[];a=e.overlay_ontop;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)eg[parseInt(b[a],10)-1]=!0;Tc=null;a=e.overlay_order;null==a&&(a=e.overlay_zorder);if(null!=a)for(b=a.split(","),Tc=Array(b.length),a=0;a<b.length;a++)Tc[parseInt(b[a],10)-1]=a;gc=null;a=e.overlay_links;if(null!=a)for(b=a.split(","),gc=Array(b.length),a=0;a<b.length;a++)gc[a]=parseInt(b[a],10);sh=[];W=null;a=e.overlay_slice;if(null!=a)for(b=a.split(","),a=0;a<b.length;a++)sh[parseInt(b[a],
10)-1]=!0;th=!0;z(e.slice_smoothing,"f")&&(th=!1);zd=null;a=e.overlay_clear;if(null!=a)for(b=a.split(","),zd=Array(b.length),a=0;a<b.length;a++)zd[a]=b[a].trim().toLowerCase();uh=!1;a=e.transparency;null!=a&&(b=a.split(","),1==b.length?vh=wh=xh=parseInt(b[0],10):(vh=parseInt(b[0],10),wh=parseInt(b[1],10),xh=parseInt(b[2],10)),uh=!0);fg=!1;a=e.transparency_list;if(null!=a){b=a.split(",");yh=[];for(a=0;a<b.length;a++)yh[parseInt(b[a].trim(),10)-1]=!0;fg=!0}$e=null;a=e.overlay_transparent_amount;if(null!=
a)for(b=a.split(","),$e=Array(b.length),a=0;a<b.length;a++)$e[a]=parseFloat(b[a])/100;Uc=null;a=e.overlay_zoom;if(null!=fc&&null!=a)for(b=a.split(","),Uc=Array(b.length),a=0;a<b.length;a++)if(Uc[a]=1,z(b[a],"n")||z(b[a],"f"))Uc[a]=0;else if(z(b[a],"d")||z(b[a],"h"))Uc[a]=-1;vb=null;zh=[];a=e.overlay_preserve_list;if(null!=fc&&null!=a)for(b=a.split(","),vb=Array(b.length),a=0;a<b.length;a++){vb[a]=!0;if(z(b[a],"n")||z(b[a],"f"))vb[a]=!1;if(z(b[a],"a")||z(b[a],"A"))zh[a]=!0}ma=null;if(null!=fc&&null!=
vb)for(b=e.overlay_preserve.replace(/&/g,",&,").split(","),d=e.overlay_preserve_position,null!=d&&(d=d.split(",")),c=0,ma=Array(vb.length),a=S=0;a<vb.length;a++)if(vb[a]){ma[a]=[];Q=0;do{ma[a][Q]=[];for(g=0;4>g;g++)ma[a][Q][g]=parseInt(b[S].trim(),10),S+=1;ma[a][Q][2]=ma[a][Q][2]-ma[a][Q][0]+1;ma[a][Q][3]=ma[a][Q][3]-ma[a][Q][1]+1;null!=d?(ma[a][Q][4]=parseInt(d[c],10),ma[a][Q][5]=parseInt(d[c+1],10),c+=2):(ma[a][Q][4]=ma[a][Q][0],ma[a][Q][5]=ma[a][Q][1]);S<b.length&&"&"==b[S].trim()?(S+=1,Q+=1,g=
!0):g=!1}while(g)}af=0;Ah=" ";Dc="white";ie="transparent";je="14pt arial";Bh=!1;a=e.times_label_style;null!=a&&(b=a.split(","),Dc=b[0].trim(),1<b.length&&(af=Math.floor(60*parseFloat(b[1]))),1<b.length&&(af="?"==b[1].trim()||"auto"==b[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(b[1]))),2<b.length&&(Ah=b[2].trim()),3<b.length&&(ie=b[3].trim()),4<b.length&&(je=b[4].trim()),5<b.length&&-1!=b[5].trim().indexOf("t")&&(Bh=!0));0==Dc.indexOf("0x")&&(Dc="#"+
Dc.substring(2));0==ie.indexOf("0x")&&(ie="#"+ie.substring(2));Ad=parseInt(je,10);Ii=new ob("black","white",je,"black",20,5,5);Ch=!1;Ch=z(e.to_from_lock,"t")?!0:!1;a="black";g="white";l="14px arial";d=null;Q=S=c=10;Dh=Eh=" ";gg=Bd=null;a=e.dirspd_display_style;null!=a&&(b=a.split(","),a=b[0].trim(),g=b[1].trim(),l=b[2].trim(),Dh=b[3],Eh=b[4],5<b.length&&(d=b[5].trim(),c=parseInt(b[6],10),S=parseInt(b[7],10),Q=parseInt(b[8],10)),gg=new ob(a,g,l,d,c,S,Q));d="black";c="white";S="14px arial";Q=null;k=
l=g=10;a=e.tipbox_display_style;null!=a&&(b=a.split(","),d=b[0].trim(),c=b[1].trim(),S=b[2].trim(),3<b.length&&(Q=b[3].trim(),g=parseInt(b[4],10),l=parseInt(b[5],10),k=parseInt(b[6],10)));Fh=new ob(d,c,S,Q,g,l,k);Cd=null;ja=e.image_base;null!=ja?Cd=ja=ja.trim():ja=null!=e.image_only_base?e.image_only_base.trim():null;Gh=ja;a=e.overlay_base;null!=a&&(wb=a.trim());bf=!0;z(e.zip_only,"f")&&(bf=!1);Vc=!1;a=e.zip_filename;null!=a&&(Vc=!0,hg=a.trim());td=!0;a=e.filenames;null==a&&(a=e.background_filenames);
null!=a&&Ji(a);a=e.basename;null!=a&&(d=e.base_starting_number,c=0,S=1,null!=d&&(b=d.split(","),c=parseInt(b[0],10),1<b.length&&(S=parseInt(b[1],10))),t=e.num_frames,null==t&&(t=e.num_images),t=parseInt(t,10),Ki(a,c,S));ig=!0;b=e.zip_static;if(z(b,"f")||z(b,"n"))ig=!1;jg=!0;b=e.background_static;if(z(b,"f")||z(b,"n"))jg=!1;a=e.overlay_filenames;null!=a&&Li(a);Qa=null;a=e.image_preserve;if(null!=a)for(b=a.split(","),Qa=[],a=0;a<b.length;a++)Qa[a]=parseInt(b[a].trim(),10),1<a%4&&(Qa[a]=Qa[a]-Qa[a-2]+
1);Hh=!1;z(e.keep_enhancement,"t")&&(Hh=!0);Ih=!0;z(e.keep_zoom,"f")&&(Ih=!1);Dd=kg=0;Jh=!1;a=e.hide_bottom;null!=a&&(b=a.split(","),kg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Jh=!0));Ed=lg=0;Kh=!1;a=e.hide_top;null!=a&&(b=a.split(","),lg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Kh=!0));Fd=mg=0;Lh=!1;a=e.hide_left;null!=a&&(b=a.split(","),mg=parseInt(b[0].trim(),10),1<b.length&&z(b[1],"t")&&(Lh=!0));Gd=ng=0;Mh=!1;a=e.hide_right;null!=a&&(b=a.split(","),ng=parseInt(b[0].trim(),
10),1<b.length&&z(b[1],"t")&&(Mh=!0));Nh=!1;z(e.hide_background,"t")&&(Nh=!0);Oh="<div>";Ph=300;Qh=500;a=e.popup_style;null!=a&&(Oh='<div style="'+a+'">');a=e.popup_window_size;null!=a&&(b=a.split(","),Qh=b[0],Ph=b[1]);Rh=!1;a=e.wheel_frames;null!=a&&(Rh=!0,pa.useWheel(H.wheel));Sh=Ga=!1;z(e.active_zoom,"t")&&(null==La&&(Ga=!0),pa.useWheel(H.wheel));og=!1;z(e.cycle_zoom,"t")&&(og=!0);a=e.initial_zoom;null!=a&&(b=a.split(","),Ec="auto"!=b[0].toLowerCase()?parseFloat(b[0]):"auto",1<b.length?(ke=parseInt(b[1],
10),Th=parseInt(b[2],10)):ke=-1,Uh=!0);Hd=1;Id=!1;ua=null;a=e.zoom_scale;if(null!=a)if(b=a.split(","),1===b.length)z(a,"hi_res")?(Id=!0,Hd=0):Hd=parseFloat(a);else{ua=Array(b.length);for(a=0;a<b.length;a++)ua[a]=parseFloat(b[a]);Id=!0}Wc=9999999;a=e.maximum_zoom;null!=a&&(Wc=parseFloat(a));cf=!0;z(e.use_progress_bar,"f")&&(cf=!1);a=e.dwell;null!=a&&(b=a.split(","),Ha=parseInt(b[0].trim(),10),1<b.length&&(hc=parseInt(b[1].trim(),10),10>hc&&(hc=10),Xc=parseInt(b[2].trim(),10),pg=parseInt(b[3].trim(),
10)));a=e.rate;null!=a&&(b=a.split(","),Ha=Math.round(1E4/parseFloat(b[0].trim())),1<b.length&&(hc=Math.round(1E4/parseFloat(b[2].trim())),10>hc&&(hc=10),Xc=Math.round(1E4/parseFloat(b[1].trim()))));a=e.frame_times_template;null!=a&&(b=a.split(","));Jd=27;a=e.mp4_quantization;null!=a&&(Jd=parseInt(a,10),10>Jd||51<Jd)&&(Jd=27);xb=null;a=e.times;if(null!=a){b=a.split(",");xb=Array(b.length);for(a=0;a<b.length;a++)xb[a]=parseInt(b[a].trim(),10);ba(xb)}a=e.extrap_times_filename;if(null!=a){xb=[];var h=
new XMLHttpRequest;h.open("get",a,!0);h.onload=function(){for(var a=h.responseText.split("\n"),b=0;b<a.length;b++){var d=a[b].split(" ");if(3==d.length){d[2].trim();var g=parseInt(d[0],10)-1;xb[g]=100*parseInt(d[2].substring(0,2),10)+parseInt(d[2].substring(3,5),10)+parseInt(d[2].substring(6,8),10)/30}}ba(xb)};h.send()}le=null;a=e.extrap_times_template;null!=a&&(le=RegExp(a));Vh=["Click on target's initial position","Click on target's final position","Move pointer around or click here to select target"];
Wh=10;z(e.extrap_prompts_position,"bot")&&(Wh=9999);a=e.extrap_prompts;null!=a&&(Vh=a.split(","));df=["Click on first point to mark","Save points","Remove last point"];a=e.mark_prompts;null!=a&&(df=a.split(","));ef=!0;z(e.mark_close,"f")&&(ef=!1);qg="12pt Arial";Xh="white";a=e.mark_prompts_style;null!=a&&(b=a.split(","),qg=b[0].trim(),1<b.length&&(Xh=b[1].trim()));Yh=e.controls;ia("controls = "+e.controls);ia("bottom_controls = "+e.bottom_controls);Yc=ff=ic=jc=yb=zb=gf=Lb=null;null!=Yh&&mb(Yh,!0);
Zh=e.bottom_controls;null!=Zh&&mb(Zh,!1);Zc=!1;a=e.probe_table;null!=a&&q(a);b=e.enhance_filename;null==b&&(b=e.enhance_table);if(null!=b){ia("Reading enhancement table...");Zc=!1;h=new XMLHttpRequest;Ab=[];$c=[];hf=[];ad=[];kc=[];var T,Fc,m;cb=[];db=[];eb=[];me=[];v=-1;$h=!0;var rg=!1,r,A,y,n,F,x,I,R,G,C,K,L,D;h.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var d=a[b].replace(/\s+/g," ").trim(),g=d.indexOf("#");if(0!=g)if(0<g&&(d=d.substring(0,
g)),g=d.split(","),0==g[0].indexOf("*"))v++,Ab[v]=Array(256),ad[v]=Array(256),$c[v]=Array(256),kc[v]=Array(256),cb[v]=Array(256),db[v]=Array(256),eb[v]=Array(256),me[v]=Array(256),Ab[v]=Array(256),hf[v]=1<g.length?g[1].trim():"None",T=" ",Fc="Value =",m=1,d=p("option"),d.innerHTML=g[0].substring(1),d.value=v,null!=Da&&Da.add(d);else{var c=d.indexOf("value");0>c&&(c=d.indexOf("probe"));rg=!1;C=K=0;0<c&&(g=d.substring(c+1),d=d.substring(0,c),c=g.indexOf("="),g=g.substring(c+1),g=g.split(","),1==g.length?
(Fc=g[0].trim(),m=-1,rg=!1):(C=parseFloat(g[0].trim()),K=parseFloat(g[1].trim()),2<g.length&&(m=parseInt(g[2],10)),3<g.length&&(T=Mi(g[3].trim())),4<g.length&&(Fc=g[4].trim()),rg=!0));d=d.split(" ");r=parseInt(d[0].trim(),10);A=parseInt(d[1].trim(),10);y=A-r;n=parseFloat(d[2].trim());F=parseFloat(d[3].trim());x=parseFloat(d[4].trim());I=parseFloat(d[5].trim());R=parseFloat(d[6].trim());G=parseFloat(d[7].trim());L=D=255;9<d.length&&(L=parseFloat(d[8].trim()),D=parseFloat(d[9].trim()));for(d=r;d<=A;d++)0===
y?(cb[v][r]=n,db[v][r]=x,eb[v][r]=R,me[v][r]=L):(cb[v][d]=Math.round(n+(F-n)*(d-r)/y),db[v][d]=Math.round(x+(I-x)*(d-r)/y),eb[v][d]=Math.round(R+(G-R)*(d-r)/y),me[v][d]=Math.round(L+(D-L)*(d-r)/y)),ad[v][d]=Fc,$c[v][d]=T,kc[v][d]=m,rg&&(Ab[v][d]=C+(K-C)*(d-r)/y)}}-1!=ub&&w[ub].checked&&(Da.disabled=!1);Zc=!0;f()};h.open("get",b,!0);h.send()}else f()}function f(){var b=e.sprite_filenames;if(null!=b){var a=b.split(",");sg=0;qa=[];b=e.sprite_images_offset;bd=-1;null!=b&&(bd=parseInt(b,10)-1);for(b=0;b<
a.length;b++){qa[b]=new Image;qa[b].gotit=!1;qa[b].inx=b;qa[b].fromfile=!0;var g="/";0<a[b].indexOf("?")&&(g="?");qa[b].zoomme=0<a[b].indexOf(g+"zoom");qa[b].anim=0<a[b].indexOf(g+"animate");g=a[b].indexOf(g);0<g&&(a[b]=a[b].substring(0,g));qa[b].onload=function(){qa[this.inx].gotit=!0;sg++;sg==a.length&&h()};qa[b].src=a[b].trim()}}else h()}function h(){for(var b=Object.keys(e),a=0;a<b.length;a++)z(b[a],"hotspot")&&Yb("hotspot="+e[b[a]]);td?H.getFOF():(Gc=!0,Xb())}function q(b){var a=new XMLHttpRequest;
Ab=[];hf=[];$c=[];var g=" ";ad=[];var d="Value=";kc=[];var c=1;cd=[];tg=[];cb=[];db=[];eb=[];var e,f=-1;v=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var B=a[b].replace(/\s+/g," ").trim().split(","),S=B[0].split(" ");if(0==S[0].indexOf("*"))v++,Ab[v]=[],ad[v]=[],$c[v]=[],kc[v]=[],cb[v]=[],db[v]=[],eb[v]=[],tg[v]=[],cd[v]=[],f=-1,hf[v]=1<B.length?B[1].trim():"None",l=1;else if(0!=l){f++;var k=Array(3);Ab[v][f]=parseFloat(S[0]);cb[v][f]=
parseInt(S[1].trim(),10);db[v][f]=parseInt(S[2].trim(),10);eb[v][f]=parseInt(S[3].trim(),10);0!=f&&(k[0]=cb[v][f]-cb[v][f-1],k[1]=db[v][f]-db[v][f-1],k[2]=eb[v][f]-eb[v][f-1],e=0,Math.abs(k[1])>Math.abs(k[e])&&(e=1),Math.abs(k[2])>Math.abs(k[e])&&(e=2),tg[v][f-1]=e,cd[v][f-1]=k,0==cd[v][f-1][e]&&(cd[v][f-1][e]=1));1<B.length&&(0==B[1].trim().indexOf('"')?(c=-1,B=B[1].trim(),d=B.substr(1,B.length-2),g=""):(c=parseInt(B[1],10),2<B.length&&(g=Mi(B[2].trim())),3<B.length&&(d=B[3].trim())));ad[v][f]=d;
kc[v][f]=c;$c[v][f]=g}}Zc=!0};a.open("get",b,!0);a.send()}function E(b){b=b.split(",");var a=b[0].trim();"PS"===a?(lc=new fj,lc.init(b)):"CE"==a?(lc=new gj,lc.init(b)):"LCC"==a?(lc=new hj,lc.init(b)):(lc=null,ug=parseFloat(b[0]),vg=parseFloat(b[1]),Ni=parseFloat(b[2]),wg=parseFloat(b[3]),0<vg&&0>wg&&(wg+=360));null==e.coordinates_display_style&&(Pe="Lat = ",Qe=" Lon = ");vd=!0}function Hb(b){var a=new XMLHttpRequest;a.onload=function(){c(this.responseText.split("\n"))};a.open("get",b+"?"+Math.round(1E5*
Math.random()),!0);a.send()}function xc(b){var a;if(null!=zd){for(a=0;a<zd.length;a++)-1!=zd[a].indexOf(b)&&(w[a].checked=!1);for(a=0;a<zd.length;a++)Jb(a)}}function ba(b){xg=Array(b.length);for(var a=0;a<b.length;a++){var g=60*Math.floor(b[a]/100)+Math.floor(b[a])%100;0===a&&(mc=g);var d=g-mc;0>d&&(d=g+1440-mc);xg[a]=d;ia("times s="+g+"  min="+xg[a])}mc+=af;1440<=mc&&(mc-=1440);0>mc&&(mc+=1440);ia("Starting minute = "+mc)}function lb(b,a){if(0!=b&&!dd)for(var g=0;g<b;g++)0==w[Ra[g].overlay].isGhost&&
(w[Ra[g].overlay].parentNode.style.visibility=a)}function na(){var b,a,g,d,c;if(yg){var e=new XMLHttpRequest;var f=0;U=[];e.onload=function(){var B=this.responseText.split("\n");ia("Processing FoF-substitute: "+ai);for(g=0;g<B.length;g++)if(!(2>B[g].length||0>B[g].indexOf(Oi))&&(U[f]=[],c=B[g].indexOf("overlay"),0<=c)){b=B[g].substring(c);c=b.indexOf("=");0>c&&ia("!! Cannot find a = sign in "+b);a=b.substring(c+1);b=a.trim();a=b.split(",");Z=Math.max(Z,a.length);ia("numOverlays reset in fof_substitute to "+
Z);for(d=0;d<a.length;d++)U[f][d]=a[d].trim(),null!=ne&&zg[d]?U[f][d]=(ne+U[f][d]).trim():null!=wb?U[f][d]=(wb+U[f][d]).trim():null!=ja&&(U[f][d]=(ja+U[f][d]).trim());f+=1}ia("Number of frames "+t+"... number of fof_sub frames = "+f);Le()};e.open("get",ai+"?"+Math.round(1E5*Math.random()),!0);e.send()}else Le()}function Le(){0!=Bb?lb(Bb,"visible"):0!=bi&&lb(bi,"hidden");Gc=!0;Xb()}function rd(b,a){Kd||(tb.height=a,tb.width=b,Ac.height=a,Ac.width=b,oe.height=a,oe.width=b,jf.height=a,jf.width=b,pe=
jf.getContext("2d"),P=2*Math.floor(b/2),O=2*Math.floor(a/2),ge&&(b=kf*O/P,a=kf,b<qe&&(a=qe*P/O,b=qe),ra=a,sa=b),lf=P/2-100,mf=O/2-10,I=1*ra/P,G=1*sa/O,Ia=Math.floor(sa/K),Ja=Math.floor(ra/C),Xa.style.height=O+"px",Xa.style.width=P+"px",Hc.style.height=O+"px",Hc.style.width=P+"px",re.style.height=O+"px",re.style.width=P+"px",Me(t,!1),ci&&(ci=!1,null!=se&&se()))}function Qf(){for(var b=0,a={},g=0;g<t;a={$jscomp$loop$prop$ii$2:a.$jscomp$loop$prop$ii$2},g++){a.$jscomp$loop$prop$ii$2=g;var d=null==ja?
za[g]:za[g].substring(za[g].lastIndexOf("/")+1);(d=di.file(d))?d.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Ic[a.$jscomp$loop$prop$ii$2]=URL.createObjectURL(d);b++;b>=t&&Oa()}}(a),function(a){return function(){Ic[a.$jscomp$loop$prop$ii$2]=null;b++;b>=t&&Oa()}}(a)):(Ic[a.$jscomp$loop$prop$ii$2]=null,b++,b>=t&&Oa())}}function Oa(){var b=0;if(0==Z)Ib();else for(var a=0;a<t;a++){Jc[a]=[];for(var g={},d=0;d<Z;g={$jscomp$loop$prop$ii$6:g.$jscomp$loop$prop$ii$6,$jscomp$loop$prop$jj$7:g.$jscomp$loop$prop$jj$7},
d++){g.$jscomp$loop$prop$ii$6=a;g.$jscomp$loop$prop$jj$7=d;var c=null==wb&&null==ja?U[a][d]:U[a][d].substring(U[a][d].lastIndexOf("/")+1);(c=di.file(c))?c.async("arraybuffer").then(function(a){return function(d){d=new Blob([d]);Jc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=URL.createObjectURL(d);b++;b>=t*Z&&Ib()}}(g),function(a){return function(){Jc[a.$jscomp$loop$prop$ii$6][a.$jscomp$loop$prop$jj$7]=null;b++;b>=t*Z&&Ib()}}(g)):(Jc[a][d]=null,b++,b>=t*Z&&Ib())}}}function Xb(){if(Vc){var b=
new XMLHttpRequest,a=null==Cd?hg:Cd+hg;ig||(a=a+"?"+Math.round(1E5*Math.random()));b.open("GET",a,!0);b.responseType="arraybuffer";Ic=[];Jc=[];b.addEventListener("progress",function(a){a.lengthComputable&&ya("Loading ZIP file",a.total,a.loaded)});b.onload=function(a){(new JSZip).loadAsync(this.response).then(function(a){di=a;Qf()},function(){ia("Unable to read ZIP file: "+hg)})};b.send()}else Ib()}function Ib(){var b,a,g;void 0!=nf&&nf(!1);var d="?"+Math.round(1E4*Math.random()),c=[];c[0]=Mb;null!=
Cb&&(Cb.disabled=!0);null!=Nb&&(Nb.disabled=!0);for(b=1;b<t;b++)c[b]=b<=Mb?b-1:b;Sa=Array(t);nc=Ta=0;ei=cf;Ag&&(Ma.max=t);Kd&&(Ld||Sc)&&(oc=[],Ya=[],ed=[],Bg=[],of=[]);null!=Da&&(Hh?null==ud&&(ud=Da.value):Da.selectedIndex=0);for(var e=0;e<t;e++){b=c[e];Kd&&(Ld||Sc)&&(oc[b]=p("canvas"),Ya[b]=p("canvas"));Sa[b]=new Image;Sa[b].gotit=!1;Sa[b].frameNum=b;Sa[b].onerror=function(){Ta++};Sa[b].onload=function(){Kd&&(sa=this.height,ra=this.width,qe=sa,kf=ra,Kd=!1,qh?ge?H.setWindowSize(u.offsetWidth,u.offsetHeight):
rd(P,O):rd(ra,sa),Ia=sa,Ja=ra,Uh&&("auto"==Ec&&(Ec=(I+G)/2,ke=-1),Ia/=Ec,Ja/=Ec,0>ke&&(ke=ra/2,Th=sa/2),M=Math.round(ke-ra/2/Ec),J=Math.round(Th-sa/2/Ec),C=K=Ec,1!=Ec&&(Ga=!1,H.toggleZooming()),Dd=kg,Ed=lg,Gd=ng,Fd=mg,Nc()));Vc&&null!=Ic[this.frameNum]&&URL.revokeObjectURL(Ic[this.frameNum]);if(0<pf&&!Md){Cg.height=sa;Cg.width=ra;te=Cg.getContext("2d");te.clearRect(0,0,P,O);for(var b=0;b<Za.length;b++){for(var e=Za[b].ctx.getImageData(0,0,Za[b].width,Za[b].height).data,f=te.getImageData(Za[b].xmin,
Za[b].ymin,Za[b].width,Za[b].height),B=3;B<e.length;B+=4)0!=e[B]&&(f.data[B]=b+1);te.putImageData(f,Za[b].xmin,Za[b].ymin)}Ga||(qb=!0);C==qf&&(qb=!0);Md=!0}if(Gc){Gc=!1;D=tb.getContext("2d");D.imageSmoothingEnabled=xd;D.imageSmoothingQuality=oh;D.fillStyle="blue";D.font="bold 20px Arial";k=Ac.getContext("2d");k.imageSmoothingEnabled=xd;$a=Array(t);Me(t,!0);rf&&!Aa?xa(oa(Mb)):xa(oa(m));if(0<Z)for(N=Array(t),B=0;B<t;B++)for(g=c[B],N[g]=Array(Z),a=0;a<Z;a++)if(void 0!=Kb[a+1]&&Kb[a+1]>=t&&(Kb[a+1]=t-
1),void 0==Kb[a+1]||Kb[a+1]==g)N[g][a]=new Image,N[g][a].gotit=!1,N[g][a].frameNum=g,N[g][a].overlayNum=a,N[g][a].onerror=function(){Ta++},N[g][a].onload=function(){this.gotit=!0;var a=this.frameNum;Ta++;Oc();!Ye||this.height==qe&&this.width==kf?this.overlayNum==he-1&&($a[this.frameNum]=0):(this.gotit=!1,ia("Bad image size:"+this.src));if(Sc&&this.gotit&&this.overlayNum==ub)oc[a].height=this.height,oc[a].width=this.width,ue=oc[a].getContext("2d"),ue.drawImage(this,0,0),Bg[a]=ue.getImageData(0,0,this.width,
this.height).data,Ya[a].height=this.height,Ya[a].width=this.width,ed[a]=Ya[a].getContext("2d"),ed[a].drawImage(this,0,0),of[a]=ed[a].getImageData(0,0,this.width,this.height),N[a][this.overlayNum]=null,N[a][this.overlayNum]=Ya[a],N[a][this.overlayNum].gotit=!0;else if(this.gotit&&w[this.overlayNum].hotspotIndex){var b=p("canvas");b.height=this.height;b.width=this.width;var d=b.getContext("2d");d.drawImage(this,0,0);var g=d.getImageData(0,0,this.width,this.height).data,c=g.length;var B=this.overlayNum;
var e;for(e=0;e<c;e+=4)if(0!=g[e]){0==fb&&(gb=[]);var f=g[e];var l=Math.floor(e/4/b.width);d=Math.floor(e/4%b.width);gb[fb]=new nb(d,l,"spritefn",f,"pan",null,null,B,a,null,null);fb++}}else if(this.gotit&&uh&&(!fg||fg&&yh[this.overlayNum])){b=p("canvas");b.height=this.height;b.width=this.width;d=b.getContext("2d");d.drawImage(this,0,0);l=d.getImageData(0,0,this.width,this.height);g=l.data;c=g.length;for(e=0;e<c;e+=4)g[e]===vh&&g[e+1]===wh&&g[e+2]===xh&&(g[e+3]=0);d.putImageData(l,0,0);N[a][this.overlayNum]=
null;N[a][this.overlayNum]=b;N[a][this.overlayNum].gotit=!0}this.gotit&&eg[this.overlayNum]?(Dg.clearRect(0,0,P,O),Dg.drawImage(N[a][this.overlayNum],0,0,P,O)):this.gotit&&sh[this.overlayNum]&&null!=W&&(b=p("canvas"),b.height=sa,b.width=ra,8>W.length&&(W[4]=0,W[5]=0,W[6]=ra,W[7]=sa),d=b.getContext("2d"),d.imageSmoothingEnabled=th,d.drawImage(this,W[0],W[1],W[2],W[3],W[4],W[5],W[6],W[7]),N[a][this.overlayNum]=null,N[a][this.overlayNum]=b,N[a][this.overlayNum].gotit=!0,null!=vb&&vb[this.overlayNum]&&
(N[a][this.overlayNum].origImage=this));Vc&&null!=Jc[a][this.overlayNum]&&URL.revokeObjectURL(Jc[a][this.overlayNum]);if(void 0!=Kb[this.overlayNum+1]&&Kb[this.overlayNum+1]==a)for(b=0;b<t;b++)b!=a&&(N[b][this.overlayNum]=N[a][this.overlayNum],Ta++)},b=U[g][a],void 0==ve||ve[a]||(b+=d),N[g][a].src=Vc&&(bf||Jc[g][a])?Jc[g][a]:b,nc++;if(null!=fd)for(pc=[],a=0;a<fd.length;a++)pc[a]=new Image,pc[a].gotit=!1,pc[a].onerror=function(a){Ta++},pc[a].onload=function(a){a.currentTarget.gotit=!0;Ta++;Oc()},pc[a].src=
fd[a],nc++;if(null!=Ua&&0<Ua.length)for(Ba=[],a=0;a<Ua.length;a++)if(void 0!=Ua[a])for(Ba[a]=[],g=0;g<Ua[a].length;g++)for(Ba[a][g]=[],B=0;B<t;B++)Pi(Ua[a][g],"/")?(b=U[B][a].lastIndexOf("/"),b=U[B][a].substring(0,b+1)+Ua[a][g]+U[B][a].substring(b+1),Ba[a][g][B]=new Image,Ba[a][g][B].gotit=!1,Ba[a][g][B].onerror=function(a){Ta++;Oc()},Ba[a][g][B].onload=function(a){a.currentTarget.gotit=!0;Ta++;Oc()},Ba[a][g][B].src=b,nc++):0===B?(Ba[a][g][0]=new Image,Ba[a][g][0].gotit=!1,Ba[a][g][0].onerror=function(a){Ta++;
Oc()},Ba[a][g][0].onload=function(a){a.currentTarget.gotit=!0;Ta++;Oc()},Ba[a][g][0].src=Ua[a][g],nc++):Ba[a][g][B]=Ba[a][g][0]}!Ye&&0!=this.height&&0!=this.width||this.height==qe&&this.width==kf?(this.gotit=!0,0==he&&($a[this.frameNum]=0)):(this.gotit=!1,ia("Image has invalid size:"+this.src));Ld&&this.gotit&&(B=this.frameNum,oc[B].height=this.height,oc[B].width=this.width,ue=oc[B].getContext("2d"),ue.drawImage(this,0,0),Bg[B]=ue.getImageData(0,0,this.width,this.height).data,Ya[B].height=this.height,
Ya[B].width=this.width,ed[B]=Ya[B].getContext("2d"),ed[B].drawImage(this,0,0),of[B]=ed[B].getImageData(0,0,this.width,this.height),Sa[B]=null,Sa[B]=Ya[B],Sa[B].gotit=!0);Ta++;Oc();Ih||H.resetZoom();gd=!0;Qi||(Qi=!0,Ea=!1,Ri());F(Aa)};var f=za[b];void 0!=Kb[0]&&(f=Kb[0],f>=t&&(f=t-1),f=za[f]);jg||(f+=d);Sa[b].src=Vc&&(bf||Ic[b])?Ic[b]:f;nc++}hd=Ob=!1;ha()}function fa(b,a,g,d,c,f){b.label_on=g;b.label_off=d;pb&&(b.className=f);g=null;d=e[a+"_labels"];null==d&&(d=e[a+"_label"]);null!=d&&(d=d.split(","),
b.label_on=d[0].trim(),1<d.length&&(b.label_off=d[1].trim()),2<d.length&&(g="width:"+d[2].trim()+"px;"));null!=c&&(b.title=c);b.innerHTML=b.label_on;c=a=d=e[a+"_style"];null!=d&&(d=d.split("&"),1<d.length&&(a=d[0],c=d[1]));b.style_on=(null!=g?g:"")+Kc+a;b.style_off=(null!=g?g:"")+Kc+c;null!=b.style_on&&1<b.style_on.length?b.setAttribute("style",b.style_on):(b.style_on=null,b.style_off=null)}function mb(b,a){Kc=e.buttons_style;null==Kc&&(Kc="");var g=null,d=null;g=a?e.controls_tooltip:e.bottom_controls_tooltip;
var c=b.split(",");if(null!=g){var f=g.split(",");f.length!=c.length&&(ia("!!! Number of tooltips must equal number of controls!"),f=g=null)}var k={};for(b=0;b<c.length;k={$jscomp$loop$prop$sfbounds$11:k.$jscomp$loop$prop$sfbounds$11},b++){var l=null!=g?f[b]:null;var h=c[b].trim();d=h.indexOf("/");if(0===d||0===b){0===d&&(h=h.substring(1));y=p("div");y.align=ce;var q=e.controls_style;null!=q?y.setAttribute("style",q):y.setAttribute("style","position:relative;padding:2px;width:100%;");a?(u.insertBefore(y,
Xa),sf=y,sf.id=tf+"-top-controls"):(q=e.bottom_controls_style,null!=q&&y.setAttribute("style",q),u.appendChild(y),uf=y,uf.id=tf+"-bottom-controls")}"enhance"==h.trim()&&(Da=p("select"),d=e.enhance_style,null!=d&&Da.setAttribute("style",d),null!=l&&(Da.title=l),d=p("option"),d.innerHTML=void 0==e.enhance_prompt?"Pick Enhancement":e.enhance_prompt,d.value=-1,Da.add(d),Da.addEventListener("change",H.doEnhance,!1),Ld=!Sc,Da.disabled=Ld?!1:!0,y.appendChild(Da));"custom"==h&&(gf=p("button"),fa(gf,"custom",
"On","Off",l,"custom"),y.appendChild(gf));"mp4"==h&&(Nb=p("button"),fa(Nb,"mp4","Make MP4","Stop",l,"mp4"),Nb.addEventListener("click",H.makeMP4,!1),y.appendChild(Nb));"anigif"==h&&(Cb=p("button"),fa(Cb,"anigif","Make GIF","Stop",l,"anigif"),Cb.addEventListener("click",H.makeAniGIF,!1),y.appendChild(Cb));"startstop"==h&&(Lb=p("button"),fa(Lb,"startstop","Start","Stop",l,"startstop start"),Lb.addEventListener("click",H.toggleIsLooping,!1),y.appendChild(Lb));"looprock"==h&&(we=p("button"),fa(we,"looprock",
"Rock","Loop",l,"looprock rock"),xe=1,we.addEventListener("click",H.toggleLoopRock,!1),y.appendChild(we),z(e.start_rocking,"t")&&H.toggleLoopRock());"loophalt"==h&&(ye=p("button"),fa(ye,"loophalt","Halt","Loop",l,"loophalt halt"),Db=!1,ye.addEventListener("click",H.toggleLoopHalt,!1),y.appendChild(ye));"extrap"==h&&(qc=p("button"),fa(qc,"extrap","Enable Extrap","Disable Extrap",l,"extrap"),qc.addEventListener("click",H.toggleExtrap,!1),y.appendChild(qc));z(h,"location")&&(Nd=p("button"),fa(Nd,"location",
"Show Loc","Hide Loc",l,"location"),0<h.indexOf("/on")?(L(Nd,!1,"location off"),Od=!0,Na.push(u.style.cursor),u.style.cursor=Ve):(Od=!1,u.style.cursor=Na.pop()),Nd.addEventListener("click",function(){(Od=!Od)?(L(Nd,!1,"location off"),Na.push(u.style.cursor),u.style.cursor=Ve):(L(Nd,!0,"location on"),u.style.cursor=Na.pop());ha()},!1),y.appendChild(Nd));"distance"==h&&(rc=p("button"),fa(rc,"distance","Show dist","Hide dist",l,"distance"),bc=Te=!1,rc.addEventListener("click",function(){(bc=!bc)?(L(rc,
!1,"distance off"),Na.push(u.style.cursor),u.style.cursor=Uf):(L(rc,!0,"distance on"),u.style.cursor=Na.pop())},!1),y.appendChild(rc));z(h,"probe")&&(Pd=p("button"),fa(Pd,"probe","Show probe","Hide probe",l,"probe"),0<h.indexOf("/on")?(L(Pd,!1,"probe off"),cc=!0,Na.push(u.style.cursor),u.style.cursor=We):(cc=!1,u.style.cursor=Na.pop()),Pd.addEventListener("click",function(){(cc=!cc)?(L(Pd,!1,"probe off"),Na.push(u.style.cursor),u.style.cursor=We):(L(Pd,!0,"probe on"),u.style.cursor=Na.pop())},!1),
y.appendChild(Pd));"mark"==h&&(id=p("button"),fa(id,"mark","Mark","Stop Mark",l,"mark"),ze=!0,id.addEventListener("click",function(){Eb=!Eb;va=[];Eb?(Qd=0,L(id,!1,"mark off"),null!=La&&(La.disabled=!0),Na.push(u.style.cursor),u.style.cursor=Vf):(L(id,!0,"mark on"),null!=La&&(La.disabled=!1),Qd=-1,u.style.cursor=Na.pop());ha()},!1),Si=new ob("black","white",qg,"black",20,5,5),fi=new ob("black","white",qg,"black",20,5,5),y.appendChild(id));"refresh"==h&&(ff=p("button"),fa(ff,"refresh","Refresh",null,
l,"refresh"),ff.addEventListener("click",H.reloadFOF,!1),y.appendChild(ff));"restore"==h&&(Eg=p("button"),fa(Eg,"restore","Restore",null,l,"restore"),Eg.addEventListener("click",function(a){for(a=0;a<w.length;a++)w[a].checked=w[a].restorableState;for(a=0;a<w.length;a++)Jb(a)},!1),y.appendChild(Eg));"setframe"==h&&(k.$jscomp$loop$prop$sfbounds$11=function(){var a=parseInt(Ma.value,10)-1;if(vf||Fg){for(var b=0;b<t;b++)Ka(b,0);wf=0}else if(a!=gi&&Gg){if(0==wf){for(b=0;b<t;b++)b>a?Ka(b,0):Ka(b,-1);wf=
1}else{for(b=a+1;b<t;b++)Ka(b,-1);wf=0;F(!0)}gi=a}},Ma=p("input"),pb&&(Ma.className="setframe"),Ma.type="range",Ma.min=1,Ma.max=100,Ma.value=1,xf="Frame #*",null!=l&&(Ma.title=l),q=e.setframe_label,null!=q&&(xf=q),Ae=p("span"),Ae.innerHTML=xf.replace("*",1),d="display:block;vertical-align:middle;"+e.setframe_style,Ma.setAttribute("style",d),d=p("span"),d.setAttribute("style","display:inline-block;vertical-align:top;"),Ae.setAttribute("style","display:block;vertical-align:middle;"+e.setframe_label_style),
d.appendChild(Ae),d.appendChild(Ma),y.appendChild(d),y.addEventListener("touchmove",function(a){a.stopPropagation()},!1),y.addEventListener("mousemove",function(a){a.stopPropagation()},!1),Ma.addEventListener("input",function(a){a.preventDefault();a.stopPropagation();F(!1);a=parseInt(Ma.value,10)-1;0<=$a[a]&&(xa(a),Ae.innerHTML=xf.replace("*",m+1));V()},!1),wf=0,gi=-1,Ma.addEventListener("pointerup",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Ma.addEventListener("mouseup",
function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Ma.addEventListener("change",function(a){return function(b){b.stopPropagation();a.$jscomp$loop$prop$sfbounds$11()}}(k),!1),Ag=!0);"framelabel"==h&&(Va=p("button"),pb&&(Va.className="framelabel"),Va.innerHTML="",null!=l&&(Va.title=l),hb=null,q=e.frame_labels,null!=q&&(hb=q.split(","),Va.innerHTML=hb[0]),d=Kc+e.framelabel_style,null!=d&&Va.setAttribute("style",d),d=e.framelabel_position,null!=d&&(d=d.split(","),
Va.style.position="absolute",Va.style.left=u.offsetLeft+parseInt(d[0],10)+"px",Va.style.top=u.offsetTop+parseInt(d[1],10)+"px"),y.appendChild(Va));if("autorefresh"==h||"autorefresh/off"==h)null!=Qc&&clearInterval(Qc),Yc=p("button"),fa(Yc,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",l,"autorefresh"),Yc.addEventListener("click",H.toggleAutoRefresh,!1),fe=!1,y.appendChild(Yc),"autorefresh"==h?H.toggleAutoRefresh():L(Yc,!1,"autotoggle off");"backward"==h&&(yb=p("button"),fa(yb,"backward",
"<","<",l,"step back"),yb.addEventListener("click",function(){F(!1);sb(-1);V()},!1),y.appendChild(yb));"forward"==h&&(zb=p("button"),fa(zb,"forward",">",">",l,"step forward"),zb.addEventListener("click",function(){F(!1);sb(1);V()},!1),y.appendChild(zb));if("step"==h){d=e.step_labels;var T=null!=d?d.split(","):["<",">"];yb=p("button");pb&&(yb.className="step back");yb.innerHTML=T[0];yb.addEventListener("click",function(){F(!1);sb(-1);V()},!1);d=Kc+e.step_style;null!=d&&yb.setAttribute("style",d);null!=
l&&(yb.title=l);y.appendChild(yb);zb=p("button");pb&&(zb.className="step forward");zb.innerHTML=T[1];zb.addEventListener("click",function(){F(!1);sb(1);V()},!1);null!=d&&zb.setAttribute("style",d);null!=l&&(zb.title=l);y.appendChild(zb)}"first"==h&&(Pb=p("button"),fa(Pb,"first","|<","|<",l,"firstlast first"),Pb.addEventListener("click",function(){F(!1);xa(oa(0));V()},!1),y.appendChild(Pb));"last"==h&&(Qb=p("button"),fa(Qb,"last",">|",">|",l,"firstlast last"),Qb.addEventListener("click",function(){F(!1);
xa(oa(t-1));V()},!1),y.appendChild(Qb));"firstlast"==h&&(d=e.firstlast_labels,T=null!=d?d.split(","):["<<",">>"],Pb=p("button"),pb&&(Pb.className="firstlast"),Pb.innerHTML=T[0],Pb.addEventListener("click",function(){F(!1);xa(oa(0));V()},!1),d=Kc+e.firstlast_style,null!=d&&Pb.setAttribute("style",d),null!=l&&(Pb.title=l),y.appendChild(Pb),Qb=p("button"),pb&&(Qb.className="firstlast"),Qb.innerHTML=T[1],Qb.addEventListener("click",function(){F(!1);xa(oa(t-1));V()},!1),null!=d&&Qb.setAttribute("style",
d),null!=l&&(Qb.title=l),y.appendChild(Qb));"setspeed"==h?(Rb=p("input"),pb&&(Rb.className="setspeed"),Rb.type="range",Rb.min=hc,Rb.max=Xc,Rb.value=Xc-Ha,null!=l&&(Rb.title=l),d="vertical-align:middle;"+e.setspeed_style,Rb.setAttribute("style",d),Rb.addEventListener("input",function(a){Ha=Xc-parseInt(Rb.value,10)+30;void 0!=Rd&&Rd(Ha);F(!0);V()},!1),y.appendChild(Rb)):"speed"==h&&(d=e.speed_labels,T=null!=d?d.split(","):["-","+"],ic=p("button"),pb&&(ic.className="speed slower"),ic.innerHTML=T[0],
ic.addEventListener("click",function(){Ha+=pg;jc.disabled=!1;Ha>Xc&&(Ha=Xc,ic.disabled=!0);void 0!=Rd&&Rd(Ha)},!1),d=Kc+e.speed_style,null!=d&&ic.setAttribute("style",d),null!=l&&(ic.title=l),y.appendChild(ic),jc=p("button"),pb&&(jc.className="speed faster"),jc.innerHTML=T[1],jc.addEventListener("click",function(){Ha-=pg;ic.disabled=!1;Ha<hc&&(Ha=hc,jc.disabled=!0);void 0!=Rd&&Rd(Ha)},!1),null!=d&&jc.setAttribute("style",d),null!=l&&(jc.title=l),y.appendChild(jc));"zoom"==h&&(La=p("button"),fa(La,
"zoom","Zoom","Un-zoom",l,"zoom off"),La.addEventListener("click",H.toggleZooming,!1),y.appendChild(La),Ga=!1);if("annotate"==h){Be=p("button");fa(Be,"annotate","Annotate","Finished",l,"annotate");ta=p("div");ta.setAttribute("style","position:absolute;box-sizing:content-box;height:120px;width:180px;top:20px;left:20px;z-index:15;visibility:hidden;background-color:lightgray;border-width:6px;border-style:solid;border-color:magenta;border-radius:25px;padding:10px;font:normal normal normal 16px Arial;color:black;");
ta.title="Drag this box around.  Select attributes, then go onto the image and click & drag";jd=kd=20;yf=Sb=!1;hi=3;ii=11;ld=Ce=0;r=[];ta.style["touch-action"]="none";var Fc=function(a){kd=a.clientX-ld;jd=a.clientY-Ce;ta.style.top=jd+"px";ta.style.left=kd+"px"};ta.addEventListener("mousedown",function(a){if(0!=a.clientX||0!=a.clientY)yf=!0,ld=a.clientX-kd,Ce=a.clientY-jd},!1);ta.addEventListener("mouseup",function(a){yf=!1},!1);ta.addEventListener("mouseout",function(a){yf&&Fc(a)},!1);ta.addEventListener("mousemove",
function(a){yf&&Fc(a)},!1);window.PointerEvent?(ta.addEventListener("pointerdown",function(a){"mouse"!=a.pointerType&&(ld=a.clientX-kd,Ce=a.clientY-jd)},!1),ta.addEventListener("pointermove",function(a){"mouse"!=a.pointerType&&(0==ld&&(ld=a.clientX,Ce=a.clientY),Fc(a))},!1)):ta.addEventListener("touchmove",function(a){a=a.changedTouches[0];0==ld&&(ld=a.clientX,Ce=a.clientY);Fc(a)},!1);Be.addEventListener("click",function(){if(Sb=!Sb){r=[];kd=u.offsetLeft;jd=u.offsetTop;var a=e.annotate_position;null!=
a&&(a=a.split(","),kd+=parseInt(a[0],10),jd+=parseInt(a[1],10));ta.style.top=jd+"px";ta.style.left=kd+"px";ta.style.visibility="visible";L(Be,!1,"annotate off");Ti=Ga;Ga=!1;null!=La&&(La.disabled=!0)}else ta.style.visibility="hidden",L(Be,!0,"annotate on"),Ga=Ti,null!=La&&(La.disabled=!1);ha()},!0);De=ji("Color Black White Red Green Blue Yellow Orange Cyan Magenta".split(" "),"black black white red green blue yellow orange cyan magenta".split(" "),function(a){});Lc=ji("Width 1 2 3 4 5 6 7 8 10 12 14 16 18 20 24 28 32 36 38".split(" "),
[1,1,2,3,4,5,6,7,8,10,12,14,16,18,20,24,28,32,36,38],function(a){6==Ee.selectedIndex?ii=Lc.selectedIndex:hi=Lc.selectedIndex});Lc.title="Select width or font size";Ee=ji("Type Arrow Circle Box Polygon Draw Text Line".split(" "),[-1,0,1,2,3,4,5,6],function(a){6==Ee.selectedIndex?(Tb.focus(),Tb.select(),Lc.selectedIndex=ii):Lc.selectedIndex=hi;0==De.selectedIndex&&(De.selectedIndex=2)});d=p("button");d.style.width="70px";d.style.margin="5px";d.innerHTML="Erase";d.title="Erase last item";d.addEventListener("click",
function(){0<r.length&&(r.pop(),ha())},!1);Tb=p("input");Tb.type="text";Tb.style.width="150px";Tb.style.margin="5px";Tb.title="Enter your text here, then click where you want it";Tb.value="Text input";T=e.annotate_defaults;null!=T&&(T=T.split(","),Ee.selectedIndex=parseInt(T[0],10),1<T.length&&(De.selectedIndex=parseInt(T[1],10)),2<T.length&&(Lc.selectedIndex=parseInt(T[2],10)),3<T.length&&(Tb.value=T[3].trim()));T=p("div");T.innerHTML="Annotation Tools";var v=p("div");v.appendChild(Ee);v.appendChild(De);
var n=p("div");n.appendChild(Lc);n.appendChild(d);d=p("div");d.appendChild(Tb);ta.appendChild(T);ta.appendChild(v);ta.appendChild(n);ta.appendChild(d);y.appendChild(Be);u.appendChild(ta)}"saveall"==h&&(Hg=p("button"),fa(Hg,"saveall","SaveAll","SaveAll",l,"saveall"),ki=e.saveall_prompt,sc=e.saveall_filename,d=e.saveall_list,li=null==d?["0"]:d.split(","),Hg.addEventListener("click",function(){for(var a=0;a<li.length;a++)for(var b=parseInt(li[a],10),d=0;d<za.length;d++){0===d&&null!=ki&&(sc=window.prompt(ki,
sc),null!=sc&&1>sc.length&&(sc=null));var g=null==sc?"":-1!=sc.indexOf("#")?sc.replace("#",d.toString()):sc+d;var c=document.createElement("a");c.href=0==b?za[d]:U[d][b-1];c.download=g;c.click()}},!1),y.appendChild(Hg));if("capture"==h){Ig=p("button");fa(Ig,"capture","Capture","Capture",l,"capture");var A=e.capture_prompt;Jg=e.capture_filename;null==Jg&&(Jg="haimage.png");Ig.addEventListener("click",function(){var a=Jg;if(null!=A&&(a=window.prompt(A,a),null==a))return;var b=p("canvas");b.height=tb.height;
b.width=tb.width;var d=b.getContext("2d");ze=!1;ha();d.drawImage(tb,0,0);d.drawImage(Ac,0,0);ze=!0;b.toBlob(function(b){var d=URL.createObjectURL(b),g=document.createElement("a");g.href=d;g.download=a;g.click();setTimeout(function(){URL.revokeObjectURL(b)},3E4)})},!1);y.appendChild(Ig)}"show"==h&&(Kg=p("button"),fa(Kg,"show","Show","Show",l,"show"),Lg=e.show_prompt,Ui=e.show_image_file,null==Lg&&(Lg="Right-click to save or copy the image<br> <font size='-1'>(to save in some browsers, you may need to first 'Open in New Tab')</font> <p>"),
Kg.addEventListener("click",function(){if(Ui)window.open(za[m]);else{var a=tb.toDataURL("image/png;base64;");var b=window.open();b.document.write(Lg+"<img src="+a+"></img>")}},!1),y.appendChild(Kg));"toggle"==h&&($a=[],d=e.toggle_size,null!=d?(d=d.split(","),Sd=parseInt(d[0],10),zf=parseInt(d[1],10),Af=parseInt(d[2],10)):(zf=Sd=10,Af=3),mi="red",ni="blue",oi="orange",pi=!1,z(e.toggle_layout_width,"t")&&(pi=!0),d=e.toggle_colors,null!=d&&(d=d.split(","),ni=d[0].trim(),mi=d[1].trim(),oi=d[2].trim()),
Fb=p("div"),Fb.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),Fb.style.backgroundColor=y.style.backgroundColor,Fb.align=ce,Mg=new PEvs(Fb,H.togdown,H.togup,null,H.togdown,null,null),Mg.setHysteresis(0),md=p("canvas"),md.height=2*zf,Ng=md.getContext("2d"),Fb.appendChild(md),a?u.insertBefore(Fb,Xa):u.appendChild(Fb),d=e.toggle_onoff,Bf=null,
null!=d&&(Bf=d.split(",")),Og=!0,null!=l&&(Fb.title=l));if("overlay"==h||z(h,"menu")){0==Fa&&(w=[]);T=e.overlay_tooltip;d=null;null!=T&&(d=T.split(","));T=e.overlay_radio;v=null;null!=T&&(v=T.split(","));var C=e.overlay_menu_links;n=null;null!=C&&(n=C.split(","));var E=e.overlay_labels_color;C=null;null!=E&&(C=E.split(","));var I=e.overlay_smoothing;E=null;null!=I&&(E=I.split(","));Cf=[];var G=I=dd=!1;z(h,"menu")&&(dd=!0,0<h.indexOf("/on")&&(I=!0),0<h.indexOf("/always")&&(G=!0));0==Fa&&(ve=[]);var x=
e.overlay_caching;h=null;null==x&&(x=e.overlay_static);null!=x&&(h=x.split(","));var K=!0;null!=e.overlay_nonewdiv&&(K=!1);Fa++;for(x=0;x<fc.length;x++){var R=fc[x].trim();Cf[x]=xd;null!=E&&(z(E[x],"t")||z(E[x],"y")?Cf[x]=!0:Cf[x]=!1);if(0==x||0==R.indexOf("/")){0==R.indexOf("/")&&(R=R.substr(1));if(dd){ib[Fa]=p("div");ib[Fa].dropalways=G;var D="menu"+Fa+"_labels_style";ib[Fa].setAttribute("style","text-align:left;display:block;position:absolute;border-style:solid;border-width:2px;background:#ffffff;z-index:99;visibility:"+
(I||G?"visible":"hidden")+";"+(void 0==e[D]?e.overlay_labels_style:e[D]));Pg++}else K?(Ub=p("div"),Pg++,Ub.align="center",a?u.insertBefore(Ub,Xa):u.appendChild(Ub)):(Ub=p("span"),y.appendChild(Ub));q=e.overlay_labels_style;dd||null==q||Ub.setAttribute("style",q)}if(null==n||null!=n&&n[x]==Fa){D=!1;-1!=R.indexOf("<a href=")&&(D=!0);var M=!1,J=!1,N=!1,P=!1;q=R.length;D||(0<R.indexOf("/on")&&R.indexOf("/on")==q-3&&(M=!0),0<R.indexOf("/always")&&R.indexOf("/always")==q-7&&(J=M=!0),0<R.indexOf("/hidden")&&
(N=!0),0<R.indexOf("/hotspots")&&(P=!0),-1!=R.indexOf("/")&&(R=R.substr(0,R.indexOf("/"))));null!=h?z(h[x],"y")||z(h[x],"t")?ve[x]=!0:ve[x]=!1:ve[x]=!0;w[x]=p("input");w[x].type="checkbox";w[x].value=R;w[x].id=tf+R;w[x].showMe=!(J&N)&!P;var O="vertical-align:middle;";q=e.checkbox_style;null!=q&&(O+=q);w[x].setAttribute("style",O);w[x].checked=M;w[x].restorableState=M;w[x].name=0;w[x].hotspotIndex=P;null!=Da&&x==ub&&w[x].checked&&(Da.disabled=!1);null!=Cc&&!Cc[x]&&M&&(yd=!1);w[x].addEventListener("click",
H.overClick,!1);null!=T&&(q=v[x].indexOf("/"),-1!=q&&(w[x].name=v[x].substr(q+1).trim()),z(v[x],"t")&&(w[x].type="radio",-1==q&&(w[x].name="all")));w[x].isGhost=!0;J||N||(null!=d&&(w[x].title=d[x]),J=p("label"),J.htmlFor=tf+R,null!=d&&(J.title=d[x]),J.innerHTML=R,J.name=w[x].name,R="vertical-align:middle;",null!=C&&(R=R+"color:"+C[x]+";"),J.setAttribute("style",R),R=p("span"),D||R.appendChild(w[x]),R.appendChild(J),dd?(R.setAttribute("style","display:block;margin-right:5px;"),ib[Fa].appendChild(R)):
(D="10",null!=Ze&&(D=10+Ze[x]),R.setAttribute("style","margin-left:"+D+"px;"),Ub.appendChild(R)),w[x].isGhost=!1)}}dd&&(nd[Fa]=p("button"),fa(nd[Fa],"menu"+Fa,"Show Overlay Menu","Hide Menu",l,"menu off"),nd[Fa].menuInx=Fa,nd[Fa].addEventListener("click",function(a){if("hidden"===ib[this.menuInx].style.visibility){for(a=1;a<ib.length;a++)ib[a].dropalways||"visible"!=ib[a].style.visibility||(ib[nd[a].menuInx].style.visibility="hidden",L(nd[a],!0,"menu off"));ib[this.menuInx].style.visibility="visible";
L(this,!1,"menu on")}else ib[this.menuInx].style.visibility="hidden",L(this,!0,"menu off")},!1),ib[Fa].dropalways||y.appendChild(nd[Fa]),u.insertBefore(ib[Fa],Xa));if(null==gc)for(gc=Array(fc.length),x=0;x<fc.length;x++)gc[x]=0;else for(x=0;x<fc.length;x++)Jb(x)}}Aa=!0;rf=null;q=e.start_looping;null!=q&&(d=q.split(","),z(d[0],"f")&&(Aa=!1),1<d.length&&(Mb=parseInt(d[1],10)-1,isNaN(Mb)&&(Mb=0),m=Mb),2<d.length&&(z(d[2],"t")&&(rf=!0),z(d[2],"f")&&(rf=!1)));F(Aa)}function Jb(b){var a;if(0>gc[b]){var g=
!1;for(a=0;a<fc.length;a++)gc[a]!=-gc[b]||g||(g=w[a].checked);w[b].checked=g}}function Yb(b){0==fb&&(gb=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");var a=b[4].trim(),g=b[4].indexOf("/"),d=b[4].indexOf("?"),c=-1,e=-1;-1!=g&&(c=parseInt(b[4].substring(g+1),10)-1,a=a.substring(0,g));-1!=d&&(e=parseInt(b[4].substring(d+1),10)-1,d<g||-1==g)&&(a=a.substring(0,d));gb[fb]=new nb(parseInt(b[0].trim(),10),parseInt(b[1].trim(),10),b[2].trim(),b[3].trim(),a.toLowerCase(),b[5].trim().toLowerCase(),b[6].trim(),
c,e,8<=b.length?b[7].trim():null,9==b.length?b[8].trim():null);fb+=1}function Zd(b){0==pf&&(Za=[],wa=null);var a=b.substr(b.indexOf("=")+1).trim().split("(");b=a[0].split(",");var g=b[0].trim();0==g.indexOf("0x")&&(g="#"+g.substring(2));Za[pf]=new yc(g,b[1].trim(),b[2].trim(),b[3].trim(),a[1].trim());pf+=1}function Pa(b){0==Bb&&(Ra=[]);b=b.substr(b.indexOf("=")+1).trim().split(",");Ra[Bb]=new Zb(parseInt(b[0],10)-1,parseInt(b[1],16),b[2].trim(),b[3].trim(),5==b.length?b[4].trim():"Click for details");
Bb+=1}function yc(b,a,g,d,c){this.color=b;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=a;this.value=g;this.tip=d;this.poly=c;b=c.split(",");this.xy=[];this.ymin=this.xmin=9999;for(a=this.ymax=this.xmax=0;a<b.length;a++)this.xy[a]=parseInt(b[a].trim(),10),0==a%2?(this.xy[a]<this.xmin&&(this.xmin=this.xy[a]),this.xy[a]>this.xmax&&(this.xmax=this.xy[a])):(this.xy[a]<this.ymin&&(this.ymin=
this.xy[a]),this.xy[a]>this.ymax&&(this.ymax=this.xy[a]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-this.xmin+1;this.can=p("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(a=2;a<this.xy.length;a+=2)this.ctx.lineTo(this.xy[a]-this.xmin,this.xy[a+1]-this.ymin);
this.ctx.closePath();this.ctx.fill()}function Zb(b,a,g,d,c){this.overlay=b;this.color=a;this.action=g;this.value=d;this.tip=c}function nb(b,a,g,d,c,e,f,l,k,h,q){this.x0=b;this.y0=a;this.icon=null;this.isIcon=!1;if("icon"==g)this.icon=new Image,this.icon.hotspot=this,Qg=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height;this.hotspot.width=this.width;this.hotspot.height=this.height;this.hotspot.w2=this.width/2;this.hotspot.h2=
this.height/2;this.hotspot.isIcon=!0;this.hotspot.origX=0;this.hotspot.origY=0},this.y1=this.x1=-1,this.zoomme=this.fromfile=this.anim=!1,this.icon.gotit=!1,this.icon.src=d.trim();else if("sprite"==g||"spritefn"===g){this.x0=b;this.y0=a;this.inx=parseInt(d,10)-1;Fe=!1;ph?null!=qa&&(-1!=bd?this.inx>=bd&&this.inx<=bd+qa.length&&(Fe=!0):"spritefn"===g&&(Fe=!0)):Fe=!0;if(Fe){-1!=bd&&(this.inx-=bd);if(this.inx>=qa.length)return null;this.x1=qa[this.inx].width+b;this.y1=qa[this.inx].height+a;this.width=
qa[this.inx].width;this.height=qa[this.inx].height;this.w2=this.width/2;this.h2=this.height/2;this.origY=this.origX=0;this.icon=qa[this.inx].cloneNode();this.anim=qa[this.inx].anim;this.fromfile=qa[this.inx].fromfile;this.zoomme=qa[this.inx].zoomme;this.anim&&(this.icon.setAttribute("style","position:absolute;top:0px;left:0px;visibility:hidden;"),Hc.appendChild(this.icon))}else this.x1=dc[this.inx]+b,this.y1=ec[this.inx]+a,this.width=dc[this.inx],this.height=ec[this.inx],this.w2=dc[this.inx]/2,this.h2=
ec[this.inx]/2,this.origX=ag[this.inx],this.origY=bg[this.inx],this.icon=$f,this.zoomme=this.fromfile=this.anim=!1;Qg=this.isIcon=!0;this.icon.gotit=!0}else this.width=parseInt(g,10),this.height=parseInt(d,10),this.w2=this.width/2,this.h2=this.height/2,Zf&&(this.x0=b-this.w2,this.y0=a-this.h2),this.x1=this.width+this.x0,this.y1=this.height+this.y0;this.pan=c;this.isPan=!1;"pan"===this.pan&&(this.isPan=!0);this.action=e;this.value=f;this.overlay=l;this.frame=k;this.tip=h;this.target=q}function $b(){if(Td&&
!Id){da=-1;for(var b=0;b<ua.length;b++)C>=ua[b]&&(da=b)}}function rb(){null!=lc?Ca=lc.toLatLon(ka,la):null!=ug?(Ca[0]=ug+(Ni-ug)*la/sa,Ca[1]=vg+(wg-vg)*ka/ra):(Ca[0]=Math.round(ka),Ca[1]=Math.round(la))}function sd(b,a){"popup"==b.action?(null!=Rg&&Rg.close(),Rg=window.open("","HAniSPopup","scrollbars=yes,width="+Qh+",height="+Ph),Rg.document.write(Oh+b.value+"</div>")):"link"==b.action?(a=b.value,rb(),a=a.replace("%LATITUDE%",Ca[0].toFixed(4)),a=a.replace("%LONGITUDE%",Ca[1].toFixed(4)),a=a.replace("%FRAMENUMBER%",
m+1),a=a.replace("%FRAMENUMBERINDEX%",dg[m]),window.open(a,b.target?b.target:"_blank","")):"fof"==b.action&&(ja=Gh,H.resetZoom(),H.newFOF(b.value,!0),xc(a))}function Nc(){var b=Lh?Fd/C:0;M+b<Fd&&(M=Fd-b);b=Mh?Gd/C:0;M+Ja-b>ra-Gd&&(M=ra-Ja+b-Gd);b=Kh?Ed/K:0;J+b<Ed&&(J=Ed-b);b=Jh?Dd/K:0;J+Ia-b>sa-Dd&&(J=sa-Ia-Dd+b);J=Math.round(J);M=Math.round(M)}function $d(b){var a=!1;b?Id?(da--,0>da?a=!0:(C=ua[da],K=ua[da])):(C-=.1*Hd/I,K-=.1*Hd/G):Id?(da++,da>=ua.length?(da--,og&&(a=!0)):(C=ua[da],K=ua[da])):(!og||
C!==Wc&&K!==Wc||(a=!0),C+=.1*Hd/I,K+=.1*Hd/G,C>Wc&&(C=Wc),K>Wc&&(K=Wc));a||C<=qf||K<=Df?(C=qf,K=Df,da=-1,ka=n,la=A,J=M=0,Ia=sa,Ja=ra,Fd=Gd=Ed=Dd=0,Md&&(qb=!0)):(Dd=kg,Ed=lg,Gd=ng,Fd=mg,M=ka-n/C,J=la-A/K,Ia=Math.floor(sa/K),Ja=Math.floor(ra/C),Nc(),Md&&(qb=!1));$b();void 0!=Ud&&Ud(["zoom",C,K,ka,la,n,A,M,J,Ja,Ia])}function ac(){Ef=0;Vb=Array(2);Gb=Array(2);Vd=Array(2);ab=0;Bd=null;xa(oa(0))}function F(b){Ea=!b;H.toggleIsLooping()}function ae(b,a,g,d,c,e){pe.clearRect(0,0,P,O);pe.imageSmoothingEnabled=
xd;D.imageSmoothingEnabled=xd;pe.drawImage(b,a,g,d,c,0,0,P,O);qi=pe.getImageData(0,0,P,O);od=qi.data;Sg=cb[e];Tg=db[e];Ug=eb[e];Vg=me[e];Vi=4*P*O;for(tc=0;tc<Vi;tc+=4)jb=od[tc],jb===od[tc+1]&&jb===od[tc+2]&&(od[tc]=Sg[jb],od[tc+1]=Tg[jb],od[tc+2]=Ug[jb],od[tc+3]=Vg[jb]);pe.putImageData(qi,0,0);D.drawImage(jf,0,0,P,O)}function L(b,a,c){null!=b&&(a?(null!=b.style_on&&b.setAttribute("style",b.style_on),b.innerHTML=b.label_on):(null!=b.style_off&&b.setAttribute("style",b.style_off),b.innerHTML=b.label_off),
pb&&(b.className=c))}function Ka(b,a){if(!(b>=t)&&(-2==$a[b]&&(a=-2),$a[b]=a,Ag&&1==a&&(Ma.value=b+1,Ae.innerHTML=xf.replace("*",b+1)),Og)){b=ri+b*(Sd+Af);var c=oi;0==a?c=ni:-1==a?c=mi:-2==a&&(c=rh);Ng.fillStyle=c;Ng.fillRect(b,zf/2,Sd,zf)}}function Me(b,a){Og&&(md.width=pi?parseInt(u.style.width,10):P,Ng.clearRect(0,0,md.width,md.height),ri=md.width/2-b*(Sd+Af)/2);for(var c=0;c<b;c++)a?-1!=he?Ka(c,-2):null!=Bf&&"n"==Bf[c].toLowerCase().trim()?Ka(c,-1):Ka(c,0):Ka(c,$a[c])}function xa(b){Ka(m,0);m=
b;Ka(m,1);null!=Va&&null!=hb&&null!=hb[m]&&(Va.innerHTML=hb[m]);void 0!=Ff&&Ff(m)}function oa(b){b>=t&&(b=t-1);if(0<=$a[b])return b;var a=-1,c=b;0==c&&(a=1);for(var d=0;d<t-1;d++)if(c+=a,0<=$a[c])return c;return b}function sb(b){Ka(m,0);var a=b;do 0<a?(a=oa(t-1),m+=1,m>a&&(Ge&&Ea?(m=a,b=-b,Db&&F(!1)):Db?(m=a,F(!1)):m=oa(0))):(a=oa(0),--m,m<a&&(Ge&&Ea?(m=a,b=-b,Db&&F(!1)):Db?(m=a,F(!1)):m=oa(t-1))),a=b;while(0>$a[m]);Db=Gf;void 0!=Ff&&Ff(m);xe=a;Ka(m,1);null!=Va&&null!=hb&&null!=hb[m]&&(Va.innerHTML=
hb[m])}function ob(b,a,c,d,e,f,k){this.bg=b;null!=b&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=a;null!=a&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=c;this.fontHeight=Math.round(1.1*parseInt(c,10));this.scolor=d;null!=d&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=e;this.sxoff=f;this.syoff=k}function Wa(b,a,c,d,e){k.globalAlpha=1;k.font=b.font;var g=b.fontHeight;c=c-g-6;var f=k.measureText(d).width;1==e&&
(a-=f);0==e&&(a-=f/2);5>a&&(a=5);5>c&&(c=5);c+g+3>O&&(c=O-g-6);a+3+f>P&&(a=P-f-6);k.save();k.beginPath();k.fillStyle=b.bg;null!=b.scolor&&(k.shadowColor=b.scolor,k.shadowBlur=b.sblur,k.shadowOffsetX=b.sxoff,k.shadowOffsetY=b.syoff);Hf=a-3;Wg=c;si=f+6;Xg=g+6;k.fillRect(Hf,Wg,si,Xg);k.closePath();k.restore();k.textBaseline="bottom";k.fillStyle=b.fg;k.fillText(d,a,c+g+3)}function ha(){k.clearRect(0,0,P,O);Yg=!1;if(kb){k.beginPath();k.lineWidth=2;k.strokeStyle="white";var b=ab;1<b&&(b=2);for(var a=0;a<
b;a++)1<ab&&(k.moveTo(Vb[0]/I,Gb[0]/G),k.lineTo(Vb[1]/I,Gb[1]/G)),k.moveTo(Vb[a]/I-15,Gb[a]/G),k.lineTo(Vb[a]/I+15,Gb[a]/G),k.moveTo(Vb[a]/I,Gb[a]/G-15),k.lineTo(Vb[a]/I,Gb[a]/G+15);k.closePath();k.stroke();if(3==ab){var c=aa,d=X;k.moveTo(c,d);k.fillStyle=Dc;k.fillRect(c-2,d-2,5,5);b=Wd;a=Math.round(c+If/I*He*(Wd-Vd[1]));for(var e=Math.round(d+Ie/G*He*(Wd-Vd[1])),f=0;300>f;f++){k.beginPath();k.lineWidth=1;k.strokeStyle=Dc;k.moveTo(c,d);k.lineTo(a,e);k.stroke();k.beginPath();k.lineWidth=3;k.rect(a-
2,e-2,5,5);k.stroke();if(3>a||a+3>P||3>e||e+3>O)break;d=mc+b;d=100*Math.floor(d/60)+d%60;d%=2400;Bh?(c="AM",1200<=d?(1300<=d&&(d-=1200),c="PM"):100>d&&(d+=1200),c=Math.floor(d/100)+":"+Math.floor(Math.floor(d%100)/10)+Math.floor(d%10)+" "+c):(c=d+" ",1E3>d&&(c="0"+d),100>d&&(c="00"+d),10>d&&(c="000"+d));d=0;Math.abs(Zg)<Ad+5&&(d=45*Wb);var h=e;0>ti*Zg&&0==d&&(h=e+Ad);k.font=je;c=c+" "+Ah;var l=k.measureText(c).width;k.fillStyle=ie;0===d?(k.fillRect(a+2,h-Ad-2+d,l+4,Ad+3),k.fillStyle=Dc,k.textBaseline=
"bottom",k.fillText(c,a+5,h)):(k.save(),k.translate(a+5,e),k.rotate(d),k.fillRect(2,-2,l+4,Ad+3),k.fillStyle=Dc,k.textBaseline="bottom",k.fillText(c,5,Ad),k.restore());c=a;d=e;a=Math.round(c+He*ti);e=Math.round(d+He*Zg);b+=ea}}null!=Bd&&Wa(gg,Wi,Xi,Bd,0);ze&&(Wa(Ii,9999,Wh,Vh[Ef],0),ui=Hf,vi=Wg,wi=Wg+Xg)}if(Eb){ze&&(0==Qd?Wa(fi,9999,10,df[0],0):(Wa(Si,10,10,df[1],0),Yi=Hf+si,Wa(fi,9999,10,df[2],0)),Zi=Hf,$i=Xg);k.beginPath();k.lineWidth=2;k.strokeStyle=Xh;for(b=0;b<va.length;b+=2)0==b?k.moveTo(va[b]/
I,va[b+1]/G):k.lineTo(va[b]/I,va[b+1]/G);ef&4<va.length&&k.lineTo(va[0]/I,va[1]/G);k.stroke();for(b=0;b<va.length;b+=2)k.beginPath(),k.rect(va[b]/I-2,va[b+1]/G-2,5,5),k.stroke()}if(Sb)for(b=0;b<r.length;b++){c=r[b].type;k.beginPath();k.strokeStyle=r[b].color;k.lineWidth=r[b].width;if("0"==c||"6"==c)a=Math.atan2(r[b].xe-r[b].x,r[b].ye-r[b].y),e=r[b].x+r[b].width*Math.sin(a),f=r[b].y+r[b].width*Math.cos(a),k.beginPath(),k.moveTo(e,f),k.lineTo(r[b].xe,r[b].ye),"0"==c&&(c=12+r[b].width/5,d=30*Wb,k.moveTo(e+
c*Math.sin(a-d),f+c*Math.cos(a-d)),k.lineTo(e,f),k.lineTo(e+c*Math.sin(a+d),f+c*Math.cos(a+d)));else if("1"==c)k.arc(r[b].x,r[b].y,r[b].size,0,2*Math.PI);else if("2"==c)k.rect(r[b].x-r[b].size,r[b].y-r[b].size,2*r[b].size,2*r[b].size);else if("3"==c){k.moveTo(r[b].xp[0],r[b].yp[0]);for(e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],r[b].yp[e]);k.lineTo(r[b].xp[0],r[b].yp[0])}else if("4"==c)for(k.moveTo(r[b].xp[0],r[b].yp[0]),e=1;e<r[b].xp.length;e++)k.lineTo(r[b].xp[e],r[b].yp[e]);else"5"==c&&(k.fillStyle=
r[b].color,k.font=r[b].width+"pt arial",a=k.measureText(r[b].text).width,k.fillText(r[b].text,r[b].x-a/2,r[b].y+r[b].width/2));k.stroke()}hd&&(aa=pa.getX(),n=aa*I,ka=M+n/C,X=pa.getY(),A=X*G,la=J+A/K,k.beginPath(),k.strokeStyle=jh,k.lineWidth=3,k.moveTo($g/I,ah/G),k.lineTo(Jf/I,Kf/G),k.stroke(),k.closePath(),rb(),vd?(pd=Wb*Xd[0],qd=Wb*Ca[0],Je=Wb*Xd[1],Ke=Wb*Ca[1],bh=Math.pow(Math.sin((qd-pd)/2),2)+Math.cos(pd)*Math.cos(qd)*Math.pow(Math.sin((Ke-Je)/2),2),bh=12742.02*Ue*Math.asin(Math.min(1,Math.sqrt(bh))),
b=" "+bh.toFixed(Wf)+" "+wd+" ",de&&(a=z(de,"t")?(Math.atan2(Math.sin(Ke-Je)*Math.cos(qd),Math.cos(pd)*Math.sin(qd)-Math.sin(pd)*Math.cos(qd)*Math.cos(Ke-Je))/Wb+360)%360:(Math.atan2(Math.sin(Je-Ke)*Math.cos(pd),Math.cos(qd)*Math.sin(pd)-Math.sin(qd)*Math.cos(pd)*Math.cos(Je-Ke))/Wb+360)%360,b=b+" ("+a.toFixed(0)+"\u00b0)")):(a=Pc*(Xd[0]-Ca[0]),e=Se*(Xd[1]-Ca[1]),b=" "+Math.sqrt(a*a+e*e).toFixed(Wf)+" "+wd+" ",de&&(a=Math.atan2(-a,e)/Wb,0>a&&(a+=360),z(de,"f")&&(a+=180),360<a&&(a-=360),b=b+" ("+a.toFixed(0)+
"\u00b0)")),Wa(Gi,Jf/I+10,Kf/G,b,-1));Ob&&Wa(Fh,xi,yi,zi,-1);if(cc||Od||Xe)if(aa=pa.getX(),n=aa*I,X=pa.getY(),A=X*G,0<=n&&0<=A){ka=M+n/C;la=J+A/K;if(Od){rb();b=Ca[1];vd&&180<b&&(b-=360);vd&&360<b&&(b-=360);aj=Pe+Ca[0].toFixed(Tf)+"  "+Qe+b.toFixed(Tf);b=X;if(hd||Ob)b=X+ih.fontHeight+6;Wa(ih,aa+10,b,aj,-1)}if(Xe)for(k.fillStyle=nh,b=0;b<fb;b++)if(a=gb[b],a.isPan){if(ka>=a.x0&&ka<=a.x1&&la>=a.y0&&la<=a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect((a.x0-M)*C,(a.y0-J)*K,a.width*C,a.height*K);
break}}else if(n>a.x0&&n<a.x1&&A>a.y0&&A<a.y1){(-1===a.overlay||w[a.overlay].checked)&&k.fillRect(a.x0,a.y0,a.width,a.height);break}if(cc&&Zc&&gd)if(ka=Math.round(ka),la=Math.round(la),Xf)bb.clearRect(0,0,1,1),bb.drawImage(Sa[m],ka,la,1,1,0,0,1,1),ca=bb.getImageData(0,0,1,1).data,Y=0,be(!1);else for(a=0;a<Z;a++)if(b=Z-a-1,N[m][b].gotit&&w[b].checked&&(b==ub||null!=Bc[b]&&0<=Bc[b])){bb.clearRect(0,0,1,1);b==ub?bb.drawImage(oc[m],ka,la,1,1,0,0,1,1):bb.drawImage(N[m][b],ka,la,1,1,0,0,1,1);ca=bb.getImageData(0,
0,1,1).data;Y=Bc[b];null!=Y&&be(b==ub||$h);break}}!qb||kb||bc||cc||null==wa||(k.drawImage(wa.can,0,0,wa.width,wa.height,wa.xmin/I,wa.ymin/G,wa.width/I,wa.height/G),Wa(Fh,(wa.xmin+wa.xmax)/2/I,(wa.ymin+wa.ymax)/2/G,wa.tip,0),Yg=!0)}function be(b){Lf=999;uc=kh;var a=Ab[Y].length-1;if(0==ca[3])uc=hf[Y];else{if(lh)vc=ca[0];else if(b)ch=0,vc=ca[0],Lf=0;else for(var c=0;c<a;c++)wc[0]=ca[0]-cb[Y][c],0>wc[0]*(cb[Y][c+1]-ca[0]-1)||(wc[1]=ca[1]-db[Y][c],0>wc[1]*(db[Y][c+1]-ca[1]-1)||(wc[2]=ca[2]-eb[Y][c],0>
wc[2]*(eb[Y][c+1]-ca[2]-1)||(Yd=tg[Y][c],dh=wc[Yd]/cd[Y][c][Yd],Ai=Math.abs(wc[Bi[Yd]]-dh*cd[Y][c][Bi[Yd]])+Math.abs(wc[Ci[Yd]]-dh*cd[Y][c][Ci[Yd]]),Ai<Lf&&(vc=c,Lf=Ai,ch=dh))));if(999>Lf)uc=ad[Y][vc],-1!=kc[Y][vc]&&(Di=Ab[Y][vc],0!=ch&&(Di+=ch*(Ab[Y][vc+1]-Ab[Y][vc])),uc=uc+" "+Di.toFixed(kc[Y][vc])+" "+$c[Y][vc]);else if(b||0<ee){var d=-1;if(b)d=ca[0];else for(c=0;c<a;c++)if(Math.abs(ca[0]-cb[Y][c])<ee&&Math.abs(ca[1]-db[Y][c])<ee&&Math.abs(ca[2]-eb[Y][c])<ee){d=c;break}-1!=d&&(uc=ad[Y][d],-1!=
kc[Y][d]&&(uc=uc+" "+Ab[Y][d].toFixed(kc[Y][d])+" "+$c[Y][d]))}}"hide"!=uc&&Wa(Hi,aa-10,X,uc,1)}function V(){if(gd)try{D.clearRect(0,0,P,O);D.globalAlpha=1;if(!Nh)if(Td&&null!=pc&&0<=da&&pc[da].gotit)D.drawImage(pc[da],M*ua[da],J*ua[da],Ja*ua[da],Ia*ua[da],0,0,P,O);else if(Sa[m].gotit&&(null!=cg?ae(Sa[m],M,J,Ja,Ia,cg):D.drawImage(Sa[m],M,J,Ja,Ia,0,0,P,O)),null!=Qa&&(D.globalAlpha=1,Sa[m].gotit))for(var b=0;b<Qa.length;b+=4)D.drawImage(Sa[m],Qa[b],Qa[b+1],Qa[b+2],Qa[b+3],Qa[b]/I,Qa[b+1]/G,Qa[b+2]/
I,Qa[b+3]/G);if(0<Z){for(b=0;b<Z;b++){var a=null!=Tc?Tc[b]:b;D.imageSmoothingEnabled=Cf[a];!eg[a]&&w[a].checked&&w[a].showMe&&(null!=$e&&(D.globalAlpha=$e[a]),Td&&0<=da&&null!=Ba&&void 0!=Ba[a]&&Ba[a][da][m].gotit?D.drawImage(Ba[a][da][m],M*ua[da],J*ua[da],Ja*ua[da],Ia*ua[da],0,0,P,O):N[m][a].gotit&&(null==Uc||1===Uc[a]?null!=Rc&&0<=Rc[a]?ae(N[m][a],M,J,Ja,Ia,Rc[a]):D.drawImage(N[m][a],M,J,Ja,Ia,0,0,P,O):0===Uc[a]&&D.drawImage(N[m][a],0,0,ra,sa,0,0,P,O)))}if(null!=vb)for(D.globalAlpha=1,b=0;b<Z;b++)if(a=
null!=Tc?Tc[b]:b,N[m][a].gotit&&(zh[a]||w[a].checked)&&vb[a])for(var c=0;c<ma[a].length;c++)D.drawImage(null!=N[m][a].origImage?N[m][a].origImage:N[m][a],ma[a][c][0],ma[a][c][1],ma[a][c][2],ma[a][c][3],ma[a][c][4]/I,ma[a][c][5]/G,ma[a][c][2]/I,ma[a][c][3]/G)}cc&&ha();ei&&Oc();if(Qg)for(D.globalAlpha=1,a=0;a<fb;a++)if(null!=gb[a]){var d=gb[a];null!=d.icon&&(d.icon.style.visibility="hidden");if((-1==d.frame||d.frame==m)&&null!=d.icon&&d.icon.gotit&&(-1==d.overlay||-1!=d.overlay&&w[d.overlay].checked)){if(d.isPan){d.zoomme&&
(d.icon.style.width=Math.round(d.width*C)+"px",d.icon.style.height=Math.round(d.height*K)+"px",d.w2=Math.round(d.width*C/2),d.h2=Math.round(d.height*K/2));var e=Math.round(((d.x0-M)*C-d.w2)/I);var f=Math.round(((d.y0-J)*K-d.h2)/G);if(d.anim){if(0>=e+d.icon.width||e>=ra||0>=f+d.icon.height||f>=sa)continue;d.icon.style.top=f+"px";d.icon.style.left=e+"px"}else D.drawImage(d.icon,d.origX,d.origY,d.width,d.height,e,f,d.width/I,d.height/G)}else D.drawImage(d.icon,d.origX,d.origY,d.width,d.height,d.x0/I,
d.y0/G,d.width/I,d.height/G);d.icon.style.visibility="visible"}}Mf&&(Nf.addFrame(D,{copy:!0,delay:Ei}),m==oa(t-1)&&(Mf=!1,F(Aa),Nf.render()))}catch(Q){ia("Error:"+Q)}}function ya(b,a,c){!cf||c>=a||(D.save(),D.fillStyle="blue",D.strokeStyle="white",D.lineWidth=3,D.strokeRect(lf,mf,200,18),D.fillRect(lf,mf,c/a*200,18),a=D.measureText(b).width,D.fillStyle="orange",D.font="14px arial",D.fillText(b,lf+100-a/2,mf+14),D.restore())}function Oc(){cf&&nc>Ta?ya("Loading Images",nc,Ta):(ei=!1,Sf&&(zc.style.visibility=
"hidden"));Ta>=nc&&(Ea||xa(oa(m)),null!=ud&&(Da.value=ud,H.doEnhance(null),ud=null),void 0!=nf&&nf(!0),null!=Cb&&(Cb.disabled=!1),null!=Nb&&(Nb.disabled=!1))}function ia(b){if(Ne&&Rf&&!Rf.closed)try{Rf.document.write(b+"<br>")}catch(a){}}function Ri(){Ea&&sb(xe);Ei=m==oa(t-1)?mh+Ha:Ha;V();setTimeout(function(){ij(Ri)},Ei)}function Of(b){for(;-180>b;)b+=360;for(;180<b;)b-=360;return b}function gj(){var b,a,c,d,e,f,k,l,h=Math.PI/180;this.init=function(d){for(var c=[],g=1;g<d.length;g++)c[g]=parseFloat(d[g]);
a=c[1];b=c[4]/c[5];e=c[6];f=c[7];d=this.toXY(c[2],c[3]);e=d[0];f=d[1]};this.toXY=function(g,B){c=b*Of(B-a)*h-e;d=-b*g*h-f;return[c,d]};this.toLatLon=function(d,c){k=-(c+f)/b/h;l=Of((d+e)/b/h+a);return[k,l]}}function fj(){var b,a,c,d,e,f,k,l,h,q,p,t,r,m,v,n,z,y,A,x,u,E,C,I,D,w,F,G,K,J,L,H=Math.PI/180;this.init=function(d){for(var c=[],g=1;g<d.length;g++)c[g]=parseFloat(d[g]);b=c[1];a=c[2];x=0==c[8]?!1:!0;u=c[6];E=u*u;C=E*E;I=C*E;D=C*C;k=c[5]/c[7];L=c[7];x?(l=Math.cos(H*b),h=Math.sin(H*b)):(l=Math.cos(-b*
H),h=Math.sin(-b*H));z=l/Math.sqrt(1-E*h*h);A=(1-u*h)/(1+u*h);n=x?Math.tan(Math.PI/4-b*H/2)/Math.pow(A,u/2):Math.tan(Math.PI/4- -b*H/2)/Math.pow(A,u/2);m=c[9];v=c[10];d=this.toXY(c[3],c[4]);m=d[0];v=d[1]};this.toXY=function(g,B){x?(e=H*g,f=H*(B-a)):(e=H*-g,f=H*(a-B));A=(1-u*Math.sin(e))/(1+u*Math.sin(e));y=Math.tan(Math.PI/4-e/2)/Math.pow(A,u/2);w=90!=b&&-90!=b?k*z*y/n:2*k*L*y/Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u));c=w*Math.sin(f);d=w*Math.cos(f);x||(c=-c,d=-d);q=c-m;p=d-v;return[q,p]};this.toLatLon=
function(g,f){c=g+m;d=f+v;w=Math.sqrt(c*c+d*d);y=90==b||-90==b?w*Math.sqrt(Math.pow(1+u,1+u)*Math.pow(1-u,1-u))/(2*k*L):w*n/(k*z);F=Math.PI/2-2*Math.atan(y);G=Math.sin(2*F);K=Math.sin(4*F);J=Math.sin(6*F);e=F+G*E/2+5*G*C/24+G*I/12+13*G*D/360+7*K*C/48+29*K*I/240+811*K*D/11520+7*J*I/120+81*J*D/1120+4279*Math.sin(8*F)*D/161280;x?(t=e/H,r=Math.atan2(c,d)/H+a):(t=-e/H,r=-Math.atan2(-c,-d)/H+a);return[t,Of(r)]}}function hj(){var b,a,c,d,e,f,h,l,k,q,p,t,u,r,m,v,n,z,y,x,A,E,C,w,D,F,I,H,G,K,J,L,M,N,P,O=Math.PI/
180;this.init=function(d){for(var g=[],e=1;e<d.length;e++)g[e]=parseFloat(d[e]);b=g[1];a=g[2];c=g[3];w=g[7];D=w*w;F=D*D;I=F*D;H=F*F;l=g[6]/g[8];k=Math.cos(O*b);q=Math.cos(O*a);t=Math.sin(b*O);p=Math.sin(a*O);A=k/Math.sqrt(1-D*t*t);E=q/Math.sqrt(1-D*p*p);y=Math.sqrt((1-t)/(1+t)*Math.pow((1+w*t)/(1-w*t),w));x=Math.sqrt((1-p)/(1+p)*Math.pow((1+w*p)/(1-w*p),w));J=(Math.log(A)-Math.log(E))/(Math.log(y)-Math.log(x));L=A/(J*Math.pow(y,J));N=l*L*Math.pow(y,J);n=g[9];z=g[10];d=this.toXY(g[4],g[5]);n=d[0];
z=d[1]};this.toXY=function(a,b){f=O*a;h=O*Of(b-c);P=Math.sin(f);C=Math.sqrt((1-P)/(1+P)*Math.pow((1+w*P)/(1-w*P),w));K=l*L*Math.pow(C,J);M=J*h;d=K*Math.sin(M);e=N+K*Math.cos(M);u=d-n;r=e-z;return[u,r]};this.toLatLon=function(a,b){d=a+n;e=b+z;K=Math.abs(J)/J*Math.sqrt(d*d+(N-e)*(N-e));C=Math.pow(K/(l*L),1/J);G=Math.PI/2-2*Math.atan(C);M=0>J?Math.atan(-d/(e-N)):Math.atan(d/(N-e));h=M/J;f=G+(D/2+5/24*F+I/12+13/360*H)*Math.sin(2*G)+(7/48*F+29/240*I+811/11520*H)*Math.sin(6*G)+(7/120*I+81/1120*H)*Math.sin(6*
G)+4279/161280*H*Math.sin(8*G);m=f/O;v=Of(c-h/O);return[m,v]}}var H=this,qh,O,P,sa,ra,qe,kf,I,G,Yh,Zh,Pb,Qb,zc,Sf,pa,Ne,Rg,Rf,Kc,eh,ge,u,y,sf,uf,Xa,tf,Hc,re,bj,cj,tb,D,bb,Ac,k,oe,Dg,Vc,hg,bf,di,ig,Ic,t,za,Rh,ib,dd,Fa,nd,Z,eg,fc,Tc,U,Jc,gc,Cd,ja,Gh,Sa,N,yg,Oi,ai,w,$e,ve,Ob,zi,xi,yi,zd,Kb,sh,W,th,ne,zg,aa,X,n,A,ka,la,Ja,Ia,M,J,ze,pb,Mb,Qi,Ea,Aa,rf,m,Ff,xe,Ge,Ud,Gc,Kd=!0,Ye,vf,Gg,Fg,Re,Oe,e,Ha,hc,Xc,Rd,nf,pg,mh,Ei,xd,oh,Cf,Da,Ld,Sc,ub,ud,Ya,oc,ed,ue,Bg,of,cg,jf,pe,qi,od,jb,Sg,Tg,Ug,Vg,Vi,tc,Rc,$a,Sd,
zf,Af,pi,Fb,ri,Mg,fh,mi,ni,oi,he,rh,gb,fb,Qg,jg,Xe,Zf,nh,sg,qa,bd,Fe,bi,Bb,Ra,ca,gh,Za,pf,qb,Md,Cg,te,wa,Yg,Cc,yd,ua,da,pc,fd,Ba,Ua,Td,hb,Va,Mc,Og,Bf,md,Ng,gd,td,Lb,zb,yb,Rb,jc,ic,Ze,Cb,Mf,Nf,Nb,Jd,id,Eb,Qd,df,qg,ef,gf,Xh,va,Si,fi,Zi,Yi,$i,qc,kb,ab,Vb,Gb,Vd,ui,Vh,vi,wi,Wh,Ii,xb,He,If,Ie,Fi,Wb,le,xg,ti,Zg,Wd,ea,Ef,mc,af,Ah,Dc,ie,je,Ad,Bh,Ch,Ui,Kg,Lg,Ig,Jg,Be,r,Hg,ki,sc,li,ta,Sb,ld,Ce,kd,jd,yf,Ti,Ee,De,Lc,Tb,hi,ii,La,Ih,Hh,Hd,C,K,qf,Df,Uh,Ec,ke,Th,Sh,Ga,Wc,Id,Pf,og,uh=!1,vh,wh,xh,fg,yh,Db,Gf,wf,gi,
we,ye,Ma,xf,Ae,Ag,rc,bc,$g,ah,Wf,Te,vd,Hf,Wg,si,Xg,ci=!0,se,hh,Jf,Kf,Gi,jh,Vf,Na,Uf,Ve,hd,Pc,Se,wd,de,pd,qd,Je,Ke,bh,Ue,Fh,dg,Nd,Od,Tf,Pe,Qe,ih,lc,Ca,Xd,aj,ug,vg,Ni,wg,Qa,Ub,Pg,Uc,vb,ma,zh,Eg,ff,Yc,Oh,Qh,Ph,Bc,cc,Pd,We,Zc,$c,ad,kc,Yd,Lf,Hi,kh,ee,lh,Xf,gg,Dh,Eh,Bd,Wi,Xi,vc,ch,dh,Bi,Ci,wc,Y,Ai,uc,Di,Ab,v,cd,$h,cb,db,eb,me,tg,hf,dj,fe,Yf,Qc,cf,$f,ag,bg,dc,ec,ph,ei,lf,mf,Ta,nc,Dd,Nh,kg,Ed,lg,Fd,mg,Jh,Kh,Mh,Lh,Gd,ng,ce,wb,jj="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),ij=window.requestAnimationFrame||
window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(b){setTimeout(b,10)},p=function(b){return document.createElement(b)},z=function(b,a){return null==b?!1:0==b.trim().toLowerCase().indexOf(a)},Pi=function(b,a){if(null!=b)return b=b.trim(),b.lastIndexOf(a)===b.length-1},Mi=function(b){void 0==eh&&(eh=p("textarea"));eh.innerHTML=b;return eh.value},ji=function(b,a,c){var d=p("select");d.style.width="70px";d.style.margin="5px";for(var g=0;g<b.length;g++){var e=
p("option");e.innerHTML=b[g];e.value=a[g];d.add(e)}d.addEventListener("change",c,!1);return d},Li=function(b){b=b.split(",");U=Array(t);for(var a=0;a<b.length;a++){var c=b[a].split("&");Z=b.length;for(var d=0;d<t;d++)0===a&&(U[d]=Array(Z)),U[d][a]=c[1==c.length?0:d].trim(),null!=wb?U[d][a]=(wb+U[d][a]).trim():null!=ja&&(U[d][a]=(ja+U[d][a]).trim())}td=!1},Ji=function(b){b=b.split(",");t=b.length;za=Array(t);for(var a=0;a<t;a++)za[a]=null!=ja?ja+b[a].trim():b[a].trim();td=!1;t>Z&&(Z=0)},Ki=function(b,
a,c){var d=b;null!=ja&&(d=ja+b);za=Array(t);for(var g=0;g<t;g++){b=g*c+a;if(0<=d.indexOf("*"))za[g]=d.replace("*",b);else if(0<=d.indexOf("?")){for(var f=d;0<=f.lastIndexOf("?");){var h=f.lastIndexOf("?");f=f.substring(0,h)+b%10+f.substring(h+1);b=Math.floor(b/10)}za[g]=f}else za[g]=d+g;ia("image filename = "+za[g])}z(e.reverse_order,"t")&&za.reverse();td=!1;t>Z&&(Z=0)};HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(b,a,c){c=window.atob(this.toDataURL(a,
c).split(",")[1]);for(var d=c.length,g=new Uint8Array(d),e=0;e<d;e++)g[e]=c.charCodeAt(e);b(new Blob([g],{type:a||"image/png"}))}});this.setup=function(b,a,g,d){void 0==a&&(a="MORdivcan");tf=a;se=g;void 0!=se&&"function"!=typeof se&&(se=null);hh=void 0!=d?d.split("\n"):null;u=document.getElementById(a);ce="center";u.align=ce;Xa=p("div");Xa.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");
tb=p("canvas");tb.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");D=tb.getContext("2d");Ac=p("canvas");Ac.setAttribute("style","position:absolute;top:0;left:0;z-index:12;");k=Ac.getContext("2d");k.imageSmoothingEnabled=!1;oe=p("canvas");oe.setAttribute("style","position:absolute;top:0;left:0;z-index:10;");Dg=oe.getContext("2d");Dg.imageSmoothingEnabled=!1;Hc=p("div");Hc.setAttribute("style","position:absolute;top:0;left:0;z-index:5;overflow:hidden;border-width:0px;padding:0px;margin:0px;");
re=p("div");re.setAttribute("style","position:absolute;top:0;left:0;z-index:10;overflow:hidden;border-width:0px;padding:0px;margin:0px;");re.appendChild(oe);jf=p("canvas");Xa.appendChild(re);Xa.appendChild(tb);Xa.appendChild(Ac);Xa.appendChild(Hc);u.appendChild(Xa);pa=new PEvs(Xa,H.down,H.up,H.move,H.drag,null,H.canTip);u.setAttribute("tabindex",0);u.addEventListener("keyup",function(a){Sb||Oe||(Fg=Gg=vf=!1,Re&&(a.preventDefault(),a.stopPropagation()))},!1);u.addEventListener("keypress",function(a){Sb||
Oe||!Re||(a.preventDefault(),a.stopPropagation())},!1);u.addEventListener("keydown",function(a){Sb||Oe||(Re&&(a.preventDefault(),a.stopPropagation()),vf=a.ctrlKey?!0:!1,Gg=a.shiftKey?!0:!1,Fg=a.altKey?!0:!1,37==a.keyCode?(F(!1),sb(-1),V()):39==a.keyCode?(F(!1),sb(1),V()):32==a.keyCode?H.toggleIsLooping():82==a.keyCode&&a.altKey&&H.resetZoom())},!1);u.addEventListener("mouseenter",function(a){u.focus({preventScroll:!0})},!1);u.style.outlineWidth="0px";u.style.outline="none";Wb=.01745329252;Mb=m=0;
Ge=!1;xe=1;Gf=Db=!1;Aa=Ea=!0;Mf=!1;fb=Z=t=0;Zf=Xe=!1;Ye=!0;Tc=null;ib=[];dd=!1;Fa=0;nd=[];Gc=!0;Ha=500;hc=100;Xc=2E3;pg=30;mh=0;Yf=6E4;Qc=null;Vc=fe=!1;bf=!0;Ic=[];Cd=wb=ja=null;yg=!1;ua=Gh=null;Td=!1;da=-1;Id=!1;Df=qf=K=C=1;Pf=!1;J=M=Ia=Ja=la=ka=A=n=X=aa=0;Uh=!1;Kd=ci=!0;Og=Sf=ge=!1;he=fh=-1;$a=[];Bb=0;Qg=!1;qa=null;bd=-1;sg=0;Fe=!1;Va=null;mf=lf=Ta=nc=0;$h=!1;Y=0;Ob=ig=jg=gd=!1;$g=ah=Jf=Kf=0;hd=bc=!1;Na=[];Na.push("default");Na.push("default");Uf="default";Od=!1;Ve="default";lc=null;Ca=[0,0];Xd=
[0,0];qb=Ag=Te=!1;yd=!0;wa=Cc=null;Eb=Yg=!1;ef=!0;Vf="default";ze=!0;va=[];cc=Xf=!1;We="default";Zc=!1;Bi=[1,0,0];Ci=[2,2,1];wc=[];Bc=[];Sc=Ld=kb=!1;af=Ef=0;Ub=uf=sf=y=Fb=null;Pg=0;Re=!0;Sb=Oe=Gg=Fg=vf=!1;Jd=27;a=p("canvas");a.height=1;a.width=1;bb=a.getContext("2d");bb.imageSmoothingEnabled=!1;Cg=p("canvas");Ne=!1;"string"===typeof b?0>b.indexOf("\n")?Hb(b):c(b.split("\n")):c(b)};this.newBasenames=function(b,a,c,d){gd=!1;Aa=Ea;F(!1);t=d;Ki(b,a,c);Gc=!0;Xb()};this.newFilenames=function(b){gd=!1;Aa=
Ea;F(!1);Ji(b);Gc=!0;Xb()};this.newOverlayFilenames=function(b){gd=!1;Aa=Ea;F(!1);Li(b);Gc=!0;Xb()};this.newProbeTable=function(b){Zc=!1;q(b.trim())};this.reloadFOF=function(){ia("reload FoF = "+Qc);xc("r");td?ej(dj,!1):(Aa=null==rf?!0:Ea,Gc=!0,Xb())};this.getFOF=function(){var b=e.file_of_filenames.trim();H.newFOF(null!=Cd?Cd+b:b,!0)};this.newFOF=function(b,a){H.resetZoom();ej(b,a)};var ej=function(b,a){var c,d,e,f,h=new XMLHttpRequest,l,k,p,r,m,v,n,w=null,z=!1;bi=Bb;gd=!1;Aa=Ea;F(!1);a&&xa(Mb);
Bb=t=0;za=[];W=Za=null;yg=!1;zg=[];for(ne=null;Hc.hasChildNodes();)Hc.removeChild(Hc.lastChild);pf=0;Td=qb=Md=!1;Ba=fd=pc=null;Ua=[];Mc=-1;U=[];var y=!1;if(null==xb||null!=le)xb=[];ia("new FOF="+b);kb&&(null!=qc&&(L(qc,!0,"extrap on"),u.style.cursor="default",F(Aa),ab=-1),kb=!1,ha());Eb&&(null!=id&&(L(id,!0,"mark on"),u.style.cursor="default",F(Aa),Qd=-1),Eb=!1,ha());h.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)if(!(2>a[c].length)&&(l=a[c].trim(),ia("FOF: "+l),0!=
l.indexOf("#")))if(0==l.indexOf("frame_labels"))m=l.split("="),hb=m[1].split(",");else if(0==l.indexOf("redirect"))for(m=l.split("="),n=m[1].split(","),ne=n[0].trim(),d=1;d<n.length;d++){var b=parseInt(n[d],10)-1;zg[b]=!0}else if(0==l.indexOf("framenumber_index_values"))m=l.split("="),dg=m[1].split(",");else if(0==l.indexOf("slice")){m=l.split("=");n=m[1].split(",");W=[];for(d=0;d<n.length;d++)W[d]=parseInt(n[d],10);W[2]=W[2]-W[0]+1;W[3]=W[3]-W[1]+1;4<W.length&&(W[6]=W[6]-W[4]+1,W[7]=W[7]-W[5]+1)}else if(0==
l.indexOf("fof_extension"))m=l.split("="),w=m[1].trim();else if(0==l.indexOf("probe_table"))m=l.split("="),Zc=!1,q(m[1].trim());else if(0==l.indexOf("image_base"))m=l.split("="),ja=m[1].trim();else if(0==l.indexOf("overlay_base"))m=l.split("="),wb=m[1].trim();else if(0==l.indexOf("high_res_basemap")){m=l.split("=");n=m[1].split(",");fd=[];for(d=0;d<n.length;d++)fd[d]=n[d].trim(),null!=ja&&(fd[d]=ja+fd[d]);Td=!0}else if(0==l.indexOf("high_res_overlay"))for(m=l.split("="),v=m[1].split("&"),e=0;e<v.length;e++){n=
v[e].split(",");Mc=parseInt(n[0].trim(),10)-1;Ua[Mc]=[];for(d=1;d<n.length;d++)Ua[Mc][d-1]=n[d].trim(),Pi(Ua[Mc][d-1],"/")||(null!=wb?Ua[Mc][d-1]=wb+Ua[Mc][d-1]:null!=ja&&(Ua[Mc][d-1]=ja+Ua[Mc][d-1]));Td=!0}else if(0==l.indexOf("high_res_zoom")){m=l.split("=");n=m[1].split(",");ua=[];for(d=0;d<n.length;d++)ua[d]=parseFloat(n[d].trim());$b()}else if(0==l.indexOf("hoverzone"))Zd(l);else if(0==l.indexOf("hotzone"))Pa(l);else if(0==l.indexOf("hotspot"))z||(gb=null,fb=0,z=!0),Yb(l);else if(0==l.indexOf("toggle_onoff"))m=
l.split("="),Bf=m[1].split(",");else if(0==l.indexOf("coordinates"))m=l.split("="),E(m[1]);else if(0==l.indexOf("fof_substitute"))b=l.indexOf("="),n=l.substring(b+1).split(","),yg=!0,ai=n[0].trim(),Oi=n[1].trim();else if(0==l.indexOf("map_scale"))m=l.split("="),n=m[1].split(","),Pc=parseFloat(n[0]),Se=1<n.length?parseFloat(n[1]):Pc;else if(0==l.indexOf("times")){m=l.split("=");n=m[1].split(",");for(c=0;c<n.length;c++)xb[c]=parseInt(n[c].trim(),10);y=!0}else{null!=le&&(b=l.match(le),null!=b&&2==b.length?
(xb.push(parseInt(b[1],10)),ia("+ + + Extrap time = "+b[1]),y=!0):ia("+ + + Cannot parse times using "+le+" from line: "+l));e=l.indexOf(" ");0>e&&(e=l.length);za[t]=l.substring(0,e).trim();null!=ja&&(za[t]=ja+za[t]);l=l.substring(e+1);b=l.indexOf('"');0<=b&&(null==hb&&(hb=[]),e=l.substring(b+1),b=e.indexOf('"'),0<=b&&(hb[t]=e.substring(0,b),0==t&&(Va.innerHTML=hb[0])));U[t]=[];b=l.indexOf("overlay");if(0<=b)for(k=l.substring(b),b=k.indexOf("="),0>b&&ia("Cannot find a = sign in "+k),p=k.substring(b+
1),k=p.trim(),p=k.split(","),Z=Math.max(Z,p.length),ia("numOverlays set to "+Z),f=0;f<p.length;f++)U[t][f]=p[f].trim(),null!=ne&&zg[f]?U[t][f]=(ne+U[t][f]).trim():null!=wb?U[t][f]=(wb+U[t][f]).trim():null!=ja&&(U[t][f]=(ja+U[t][f]).trim());t+=1}y&&ba(xb);null!=w?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(c=0;c<a.length;c++)2>a[c].length||(r=a[c].trim(),ia("ext_FOF: "+r),0!=r.indexOf("#")&&(0==r.indexOf("hotzone")?Pa(r):0==r.indexOf("hotspot")&&Yb(r)));na()},
a.onerror=function(){na()},a.open("get",w+"?"+Math.round(1E5*Math.random()),!0),a.send()):na()};dj=b;h.open("get",b+"?"+Math.round(1E5*Math.random()),!0);h.send()};this.setWindowSize=function(b,a){if(null!=u){u.style.height=a+"px";u.style.width=b+"px";u.style.padding="0px";bj=a=a-(null!=sf?sf.offsetHeight:0)-(null!=uf?uf.offsetHeight:0)-(null!=Fb?Fb.offsetHeight:0)-Pg*(null!=Ub?Ub.offsetHeight:0);cj=b;var c=a*ra/sa;c>b&&(c=b,a=b*sa/ra);a=Math.floor(a);c=Math.floor(c);Kd||(ge?rd(cj,bj):rd(c,a),ha())}};
this.drag=function(b){Eb||(aa=pa.getX(),X=pa.getY(),Sb?(b=r.length-1,r[b].xe=aa,r[b].ye=X,r[b].xp.push(aa),r[b].yp.push(X),r[b].size=Math.round(Math.sqrt(Math.pow(aa-r[b].x,2)+Math.pow(X-r[b].y,2)))):(n=aa*I,A=X*G,hd=Ob=!1,bc&&(!Te||Te&&b.shiftKey)?(Jf=n,Kf=A,hd=!0):(Ga&&K!=Df?(M=ka-n/C,J=la-A/K,Nc(),ka=Math.round(M+n/C),la=Math.round(J+A/K),void 0!=Ud&&Ud(["drag",C,K,ka,la,n,A,M,J,Ja,Ia])):Eb||kb||!qb||(wa=null,yd&&0<=n&&0<=A&&(ca=te.getImageData(n,A,1,1).data,0!=ca[3]&&(wa=Za[ca[3]-1]))),Pf=!0,
V())),ha())};this.resetZoom=function(){C=qf;K=Df;da=-1;null!=La&&(L(La,!0,"zoom on"),Ga=!1);ka=n;la=A;J=M=0;Ia=sa;Ja=ra;$b();V();Md&&(qb=!0);void 0!=Ud&&Ud(["reset",0,0])};this.canTip=function(){var b;Ob=!1;aa=pa.getX();n=aa*I;X=pa.getY();A=X*G;if(!((Eb||kb)&&A<wi&&A>vi&&n>ui)){ka=Math.round(M+n/C);la=Math.round(J+A/K);if(0!=Bb)for(b=0;b<Bb;b++)if(Ra[b].overlay>=Z)ia(" Error...hotzone overlay # "+Ra[b].overlay+" > number of overlays = "+Z);else if(w[Ra[b].overlay].checked&&(bb.clearRect(0,0,1,1),
bb.drawImage(N[m][Ra[b].overlay],ka,la,1,1,0,0,1,1),ca=bb.getImageData(0,0,1,1).data,gh=(ca[0]<<16)+(ca[1]<<8)+ca[2],gh==Ra[b].color)){Ob=!0;xi=aa;yi=X;zi=Ra[b].tip;break}if(0!=fb)for(b=fb-1;0<=b;b--)if(null!=gb[b]){var a=gb[b];if(-1==a.frame||a.frame==m)if(-1==a.overlay||w[a.overlay].checked){var c=!1;if(a.isPan)if(a.isIcon){var d=(a.x0-M)*C-a.w2;var e=(a.y0-J)*K-a.h2;n>d&&n<d+a.width&&A>e&&A<e+a.height&&(c=!0)}else d=(a.x0-M)*C,e=(a.y0-J)*K,n>d&&n<d+a.width*C&&A>e&&A<e+a.height*K&&(c=!0);else n>
a.x0&&n<a.x1&&A>a.y0&&A<a.y1&&(c=!0);if(c&&null!=a.tip){Ob=!0;xi=aa;yi=X;zi=gb[b].tip;break}}}ha()}};this.move=function(){if(!kb&&qb&&(wa=null,yd)){var b=pa.getX()*I,a=pa.getY()*G;0<=b&&0<=a&&(ca=te.getImageData(b,a,1,1).data,0!=ca[3]&&(wa=Za[ca[3]-1]))}kb&&2<=ab&&(aa=pa.getX(),n=aa*I,X=pa.getY(),A=X*G);ha()};this.down=function(){Ob&&(Ob=!1,ha());aa=pa.getX();n=aa*I;X=pa.getY();A=X*G;$g=n;ah=A;Jf=$g;Kf=ah;ka=Math.round(M+n/C);la=Math.round(J+A/K);bc&&(rb(),Xd[0]=Ca[0],Xd[1]=Ca[1]);Pf=!1;if(Sb){var b=
{};b.x=aa;b.y=X;b.xe=aa;b.ye=X;b.xp=[aa];b.yp=[X];b.type=Ee.value;b.color=De.value;b.width=Lc.value;b.text=Tb.value;b.size=0;r.push(b)}};this.up=function(b){Ob=!1;if(!Sb){if(kb||Eb){aa=pa.getX();n=aa*I;X=pa.getY();A=X*G;if(Eb){Qd=1;if(0<Qd&&A/G<$i){if(n/I>Zi){va.pop();va.pop();0==va.length&&(Qd=0);ha();return}if(n/I<Yi){ha();b=window.open("","Mark Points");b.document.write("<div>Marked Points<br>");for(var a=[],c=0;c<va.length;c+=2)ka=M+va[c]/C,la=J+va[c+1]/K,rb(),b.document.write(Ca[0].toFixed(4)+
","+Ca[1].toFixed(4)+"<br>"),0==c&&(a[0]=Ca[0],a[1]=Ca[1]);ef&&b.document.write(a[0].toFixed(4)+","+a[1].toFixed(4)+"<br>");return}}va.push(n);va.push(A);ha();return}if(3>ab)if(Vb[ab]=n,Gb[ab]=A,Vd[ab]=xg[m],0==ab)ab=1,xa(oa(t-1)),Ef=1,Bd=null;else{Fi=Vd[1]-Vd[0];If=(Vb[1]-Vb[0])/Fi;Ie=(Gb[1]-Gb[0])/Fi;if(null!=gg&&null!=Pc){c=If*Pc;var d=Ie*Se;a=Math.round(60*Math.sqrt(c*c+d*d));c=Math.atan2(c,-d)/Wb;0>c&&(c+=360);Bd=Dh+jj[Math.round(c/22.5)]+" at "+a+" "+Eh;Wi=Vb[0];Xi=0<Ie?Gb[0]-15:Gb[0]+30}a=
parseInt(je,10);ea=Math.round(Math.abs(4*(a+4)/If));Wd=Math.round(Math.abs(2*(a+4)/Ie));Wd<ea&&(ea=Wd);120<ea?ea=120*Math.floor(ea/120)+60:90<ea?ea=120:60<ea?ea=90:30<ea?ea=60:15<ea?ea=30:10<ea?ea=15:5<ea?ea=10:2<ea?ea=5:0==ea&&(ea=1);Wd=Vd[1]/ea*ea+ea;He=1;Ch&&(He=-1);ti=If*ea;Zg=Ie*ea;xa(oa(t-1));ab=3;Ef=2}else if(A/G<wi&&A/G>vi&&n/I>ui&&3==ab){ac();ha();return}ha()}if(hd)hd=!1,ha();else if(null!=rc&&Ga&&(bc=!1,L(rc,!0,"distance on")),Pf)Pf=!1;else if(b.altKey)H.resetZoom();else if(qb&&null!=wa&&
Yg)sd(wa,"z");else{aa=pa.getX();n=aa*I;X=pa.getY();A=X*G;if(0!=Bb)for(a=0;a<Bb;a++)if(Ra[a].overlay>=Z)ia(" Error...hotzone overlay # "+Ra[a].overlay+" > number of overlays = "+Z);else if(w[Ra[a].overlay].checked&&(bb.clearRect(0,0,1,1),bb.drawImage(N[m][Ra[a].overlay],Math.floor(ka),Math.floor(la),1,1,0,0,1,1),ca=bb.getImageData(0,0,1,1).data,gh=(ca[0]<<16)+(ca[1]<<8)+ca[2],gh==Ra[a].color)){sd(Ra[a],"z");return}if(0!=fb)for(a=fb-1;0<=a;a--)if(null!=gb[a]){var e=gb[a];if(!(-1!=e.frame&&e.frame!=
m||e.fromfile||-1!=e.overlay&&!w[e.overlay].checked)){var f=!1;e.isPan?e.isIcon?(c=(e.x0-M)*C-e.w2,d=(e.y0-J)*K-e.h2,n>c&&n<c+e.width&&A>d&&A<d+e.height&&(f=!0)):(c=(e.x0-M)*C,d=(e.y0-J)*K,n>c&&n<c+e.width*C&&A>d&&A<d+e.height*K&&(f=!0)):n>e.x0&&n<e.x1&&A>e.y0&&A<e.y1&&(f=!0);if(f){sd(gb[a],"s");return}}}Ga&&(qb=!1,$d(b.ctrlKey||vf||b.which&&3==b.which||b.button&&2==b.button));V();ha()}}};this.wheel=function(b){Rh?sb(b):Ga&&(aa=pa.getX(),n=aa*I,X=pa.getY(),A=X*G,ka=Math.round(M+n/C),la=Math.round(J+
A/K),$d(-1==b))};this.toggleAutoRefresh=function(){fe?(L(Yc,!1,"autorefresh off"),null!=Qc&&clearInterval(Qc),fe=!1):(L(Yc,!0,"autorefresh on"),Qc=setInterval("HAniS.reloadFOF();",Yf),fe=!0)};this.toggleLoopRock=function(){Ge?(L(we,!0,"looprock rock"),Ge=!1):(L(we,!1,"looprock loop"),Ge=!0)};this.toggleLoopHalt=function(){Db?(L(ye,!0,"loophalt halt"),Gf=Db=!1):(L(ye,!1,"loophalt loop"),Gf=Db=!0)};this.toggleExtrap=function(){kb?(null!=qc&&(L(qc,!0,"extrap on"),u.style.cursor=Na.pop(),null!=Lb&&(Lb.disabled=
!1),F(Aa),Ga=Sh,ab=-1),kb=!1,ha()):(null!=qc&&(kb=!0,Bd=null,Na.push(u.style.cursor),u.style.cursor="crosshair",L(qc,!1,"extrap off"),Aa=Ea,null!=Lb&&(Lb.disabled=!0),Ea=!1,Sh=Ga,Ga=!1,H.resetZoom(),ac(),ha()),V())};this.doEnhance=function(b){if(Ld||Sc){var a=Ya[0].height,c=Ya[0].width;b=parseInt(Da.value,10);0<=b?(Sg=cb[b],Tg=db[b],Ug=eb[b],Vg=me[b],Bc[ub]=b):Bc[ub]=null;var d=a*c*4;for(c=0;c<oc.length;c++)if(Ya[c].gotit){Ya[c].gotit=!1;var e=of[c].data;var f=Bg[c];if(0>b)for(a=0;a<d;a+=4)e[a]=f[a],
e[a+1]=f[a+1],e[a+2]=f[a+2],e[a+3]=f[a+3];else for(a=0;a<d;a+=4)jb=f[a],jb===f[a+1]&&jb===f[a+2]&&(e[a]=Sg[jb],e[a+1]=Tg[jb],e[a+2]=Ug[jb],e[a+3]=Vg[jb]);ed[c].putImageData(of[c],0,0);Ya[c].gotit=!0}}};this.overClick=function(b){var a;if(b.target.checked)for(a=0;a<w.length;a++)b.target!=w[a]&&0!=b.target.name&&b.target.name==w[a].name&&(w[a].checked=!1);yd=!0;for(a=0;a<gc.length;a++)b.target!=w[a]&&Jb(a),null!=Cc&&!Cc[a]&&w[a].checked&&(yd=!1),null!=Da&&a===ub&&(Da.disabled=!w[a].checked);V()};this.toggleIsLooping=
function(){Ea?(Ea=!1,L(Lb,!0,"startstop start")):(Ea=!0,L(Lb,!1,"startstop stop"),Gf=Db,Db=!1)};this.toggleZooming=function(){Ga?(H.resetZoom(),L(La,!0,"zoom on")):(L(La,!1,"zoom off"),Ga=!0,null!=rc&&(bc=!1,L(rc,!0,"distance on")),Md&&(qb=!0),kb&&H.toggleExtrap())};this.togup=function(b){fh=-1};this.togdown=function(b){var a=Mg.getX();Mg.getY();for(var c=ri,d=0;d<$a.length;d++){if(a>c&&a<c+Sd){if(d==fh)break;if(b.shiftKey){0<=$a[d]&&(F(!1),xa(d));break}a=0;!b.ctrlKey&&0<=$a[d]&&(a=-1);Ka(d,a);fh=
d;break}c=c+Sd+Af}};this.makeMP4=function(){var b=Nb.innerHTML;Aa=Ea;F(!1);xe=1;xa(oa(Mb));Nb.innerHTML="Working";HME.createH264MP4Encoder().then(function(a){var c,d,f,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:a.width=P,a.height=O,a.frameRate=Math.max(1,Math.round(1E3/Ha)),a.quantizationParameter=Jd,a.initialize();case 2:return V(),a.addFrameRgba(D.getImageData(0,0,P,O).data),g.yield(new Promise(function(a){return window.requestAnimationFrame(a)}),
4);case 4:if(m>=oa(t-1)){g.jumpTo(3);break}sb(1);g.jumpTo(2);break;case 3:a.finalize();Nb.innerHTML=b;c=a.FS.readFile(a.outputFilename);d=e.mp4_prompt;f=e.mp4_filename;null==f&&(f="hanimate.mp4");h=f;if(null!=d&&(h=window.prompt(d,h),null==h))return a.delete(),F(Aa),g.return();k=document.createElement("a");k.href=URL.createObjectURL(new Blob([c],{type:"video/mp4"}));k.download=h;k.click();a.delete();F(Aa);g.jumpToEnd()}})})};this.makeAniGIF=function(){if(!Mf){var b=Cb.innerHTML;Nf=new GIF({workers:4,
debug:!1,quality:10,width:P,height:O,repeat:0});Nf.on("finished",function(a){Cb.innerHTML=b;var c=e.anigif_prompt,d=e.anigif_filename;null==d&&(d="hanimate.gif");if(null!=c&&(d=window.prompt(c,d),null==d))return;c=document.createElement("a");c.href=URL.createObjectURL(a);c.download=d;c.click();setTimeout(function(){URL.revokeObjectURL(a)},3E4)});Nf.on("progress",function(a){Cb.innerHTML=Math.round(100*a)+"%"});Aa=Ea;F(!1);xe=1;Mf=!0;xa(oa(Mb));V();F(!0);Cb.innerHTML="Loading"}};this.doneLoading=function(b){nf=
b};this.getCustomButton=function(){return gf};this.dwellChanged=function(b){Rd=b};this.getDwell=function(){return Ha};this.frameChanged=function(b){Ff=b};this.getFrame=function(){return m};this.showFrame=function(b){xa(oa(b));V()};this.zoomChanged=function(b){Ud=b};this.showZoom=function(b){"reset"===b[0]?H.resetZoom():(C=b[1],K=b[2],ka=b[3],la=b[4],n=b[5],A=b[6],M=b[7],J=b[8],Ja=b[9],Ia=b[10],Nc(),V())}};
